### ISSUE TITLE
Anmeldung

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#1]
Ich habe jetzt alles durchprobiert, aber es gelingt mir nicht, mich mit meiner Landeskirchenadresse, mit der ich mich eingeladen habe, anzumelden. Es geht einfach nicht.

**Comment by empeiria** [comment]
kannst du mal gucken @beo9999 ?

**Comment by beo9999** [comment]
da kamen gleich 2 Nachrichten...
Einmal die Frage von Jörg, zum zweiten eine "assigned"-Meldung.

**Comment by staude** [comment]
@beo9999 das ist auch richtig, einmal wurdest du in der Nachricht von @empeiria mit dem at Zeichen erwähnt (so wie auch in Trello) und die andere Mail ist die benachrichtigung das das Ticket dir zugeordnet wurde

**Comment by empeiria** [comment]
ja, @beo9999 die erste Nachricht war durch die @-Mention, die zweite durch die Assignee-Einstellung.

**Comment by empeiria** [comment]
jetzt habe ich es wieder an der Backe :-)

**Comment by beo9999** [comment]
Was sollte man unter dem Tab "Preview" sehen können?

**Comment by beo9999** [comment]
<strong>bla</strong> blubb
ah, ok, HTML geht hier auch

**Comment by staude** [comment]
@beo9999 ist die Voransicht deines Textes weil du in dem Textfeld auch Markdown verwenden kannst. https://guides.github.com/features/mastering-markdown/

**Comment by staude** [comment]
Verweis auf ein Issue in einem unserer Repos. 
rpi-virtuell/rw-remote-auth-server#5
