### ISSUE TITLE
Gepinnte Aktivitäten in Mobilansicht nicht sichtbar 

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/reliwerk#100]
![image](https://cloud.githubusercontent.com/assets/870951/13117359/dd5c09ce-d59f-11e5-9de2-f4dd2b46e5f2.png)

**Comment by johappel** [comment]
Dann sollten wir die Pins vielleicht doch nicht im Widget sondern über den Aktivitäten anbringen

**Comment by staude** [comment]
Hab noch nicht geschaut. Denke mal das er im mobilen eine andere Sitebar nutzt ?!
Ist auch unglücklich das da unten zu haben, weil beim Scrollen an das Ende ja der Rest der Aktivitäten geladen wird.
