### ISSUE TITLE
Aktivitäten - Neues: Angehängter Link ist immer falsch

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#101]
Wenn man bei "Neues" auf der Aktivitätenseite einen Link eingibt, dann wird die Zielseite durch Anklicken des Links zwar aufgerufen. 
Aber der grafische Link, der unterhalb des Textbereiches automatisch erstellt wird, 

![aktivitaetenbug](https://cloud.githubusercontent.com/assets/16247643/13191348/544efc2a-d763-11e5-888a-c7b44e1383e1.JPG)

verzweigt immer an die falsche Adresse, weil der betreffende Link-String falsch ausgelesen wird. Aus "http://www.openreli.de/veranstaltungen/gottes-spuren-im-gehirn/> Michael" wird "http://www.openreli.de/veranstaltungen/gottes-spuren-im-gehirn/Michael" gemacht. Immer wird das auf die URL folgende Wort mit in den Link übernommen.

**Comment by johappel** [comment]
das kann ich nicht nachvollziehen
http://www.openreli.de/veranstaltungen/gottes-spuren-im-gehirn/ wird korrekt erkannt
allerdings "http://www.openreli.de/veranstaltungen/gottes-spuren-im-gehirn/> Michael" ist auch eine ungültieg Adresse

**Comment by johappel** [comment]
Das Problem ist in der Tat in der Anhang einer Activity, die sich mit der Activity-Edit Funktion nicht ändern lässt. Ein Problem, dass wir nicht wirklich lösen können. Müssten wir an Buddyboss weiter geben.
Workarraund: Activity löschen und mit dem korrekten Link neu eingeben,
