### ISSUE TITLE
Schriftgröße bei gruppen.rpi-virtuell.de

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#102]
Während in den neueren Blogss die Schriftarten immer größer werden, brauche ich zum Lesen der Forumsbeiträge von reliwerk - sorry, TPFKAR, ein Vergrößerungsglas.

Lässt sich das CSS so ändern, dass die Schrift ein wenig größer wird? 
Oder - Traum meiner Sehnsüchte - individuell größenverstellbar wird?

**Comment by staude** [comment]
Hallo @deuxpont 
Besteht das Problem in der aktuellen Version der Gruppen noch? In den 1 1/2 Jahren hat sich ja einiges geändert.

**Comment by deuxpont** [comment]
Problem besteht nicht mehr. Ticket kann geschlossen werden.
