### ISSUE TITLE
Link rpi-virtuell.de

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#103]
Ich mag den Link auch nicht, aber darüber hinaus funktioniert er auch nicht bei mir. 
Wenn ich dagegen reliwerk.de eintippe, komme ich sofort ins ÜBER-Menü.

**Comment by staude** [comment]
Welchen link, wo?

**Comment by deuxpont** [comment]
ein rpi-virtuell-Link lief ins Leere. Wurde von Jörg bereits gefixt. 
Aber wo wir schon beim Linkfixen sind: Wenn man aus gruppen.rpi-virtuell heraus den support-Button anklickt, landet man nicht bei github, sondern im alten rpi-virtuell-supportbereich. Ist das so geplant?
Wenn man dagegen im ÜBER-Menü den Support-Button anklickt, landet man bei github.

**Comment by staude** [comment]
Danke für den Hinweis. Ist im Plugin geändert. Wird aber noch etwas dauert bis als Update auf den Site zur Verfügung steht.
