### ISSUE TITLE
Gruppen-Tool  Löschfolgen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#105]
Wenn ich ein Doc lösche, lande ich nicht wieder auf meiner Gruppenseite, wo ich ja eigentlich arbeite, sondern ich lande im Activitystream bei allen Docs. Ich muss dann wieder in Gruppen gehen, meine Gruppe suchen, in der ich zuletzte gearbeitet habe und dort wieder auf Docs gehen.

**Comment by staude** [comment]
Dokumente sind immer im eigenen Docs Bereich und können nur zusätzlich in einer(!) Gruppe eingeblendet werden.
