### ISSUE TITLE
Gruppentool  Ordnungen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#106]
Joachim, Du hast mal vorgeschlagen, zur Übersichtlichkeit ein eigenes Doc zu eröffnen, dort eine Kapitelübersicht zu machen und diese zu verlinken. Es gibt aber keine Kapitelmöglichkeit. Ich muss jede der 25 Kompetenzen des Bildungsplanes extra verlinken, weil es keine Überschriftsmöglichkeit gibt. Oder gibt es doch eine?

**Comment by johappel** [comment]
![2016-03-08_12h40_07](https://cloud.githubusercontent.com/assets/307023/13600738/372e6682-e52b-11e5-9c69-2e25dbfa6fd8.png)

**Comment by joerglohrer** [comment]
Es gibt noch eine Möglichkeit @lehr-ruetsche: 
Du kannst mit den "Eltern" und "Kindern" arbeiten, dann werden alle zugehörigen Dokumente unter dem Doc angezeigt.
