### ISSUE TITLE
Einladen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#107]
Früher konnte ich Leute in eine Gruppe einladen und "per Email" anklicken. Jetzt ist es, wenn ich es richtig sehe, ein entweder oder. Da ich aber die lustigen Namen der Anmeldenden Personen nicht verifzieren kann, bekomme ich die Nachricht, dass irgendeine Email-Adresse schon vorhanden ist. Das heißt also, die Person ist schon Mitglied bei rpi-virtuell. Wie soll ich anhand der lustigen Namen rausfinden, wer das ist? Und erst recht, wenn da mal 40.000 Namen stehen? Das ist schwer handelbar. Müsste ich als Alternative die Person privat anschreiben, sie bitten, sich anzumelden und dann in der Gruppe um Einlass zu bitten, wenn es keine ganz offene Gruppe ist?

**Comment by johappel** [comment]
![image](https://cloud.githubusercontent.com/assets/307023/16874951/c48d85b8-4a9c-11e6-8eb7-bb6900a1aedc.png)
