### ISSUE TITLE
Gruppeneinladung annehmen führt in's Nichts

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#108]
Wenn man eine Gruppeneinladung bekommt (via mail oder "Alarmglocke") landet man hier:
![image](https://cloud.githubusercontent.com/assets/1091954/13739175/ef99e596-e9c9-11e5-9501-f103a730f4ee.png)
Ein Klick auf "Annehmen" führt zu:
![image](https://cloud.githubusercontent.com/assets/1091954/13739181/0012f85e-e9ca-11e5-93fb-ff60ebcb616b.png)
Ich würde erwarten, direkt in der angenommenen Gruppe zu landen. So muss ich sie erst wieder suchen.

**Comment by staude** [comment]
Die Idee ist das man in der Ansicht mehrere Einladungen auf einem Rutsch an-/ablehnen kann.

**Comment by joerglohrer** [comment]
Ok - Meine Wünsche greifen wahrscheinlich zu tief in's buddypress-Konzept ein.
