### ISSUE TITLE
Freunde anfragen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#109]
Es kann sein, dass ich einfach nur auf dem Schlauch stehe. Ich habe eine Übungsgruppe "Philosophie" mit drei Mitgliedern. Alle Mitglieder bin ich mit unterschiedlichen Namen. Nun bin ich heute mal nach längerem wieder auf diese Gruppe und dort auf "Mitglieder". Hinter meinen beiden "anderen Namen", die nicht Administrator sind, stand "Freund hinzufügen". Ich habe drauf geklickt um zu sehen was passiert. Das blaue Feld wandelte sich einfach in "Freundschaftsanfrage abbrechen". Und damit hatte es sich. Wenn das überall so wäre, könnte man den Sinn nicht erkennen. Oder liegt es daran, dass ich im Grund "mit mir selbst kommuniziere"? Aber das weiß das System ja eigentlich nicht. Also, diese blauen Felder sind irritierend.
![freundschaftsanfrage](https://cloud.githubusercontent.com/assets/15977289/13748076/8cd35c44-e9fb-11e5-80c6-398aff2a42de.png)

**Comment by johappel** [comment]
Die Freundschaftsanfrage, muss von dem Freund (also von der jeweils "angefragten" Person) bentwortet werden und nicht von dir selbst,

**Comment by staude** [comment]
Du hast an einen anderen Benutzer eine Freundschaftsanfrage gestellt. Solange dieser Benutzer diese noch nicht angenommen oder abgeleht hat kannst du diese Anfrage zurückziehen, daher der neue Knopf mit "Freudschaftsanfrage abbrechen". Wenn mit deinem andren Benutzer dich anmeldest wirst du eine entsprechende Meldung haben das Andrea Lehr-Ruetsche an dich eine Freunschaftsanfrage gestellt hat.

**Comment by lehrruetsche** [comment]
aber der andere Benutzer ist doch bereits drin! Ich habe als "Andrea", (Andrea gehört bereits zur Gruppe) eine Einladung von Andrea Lehr-Rütsche bekommen (Administratorin der Gruppe). D.h., ich verschicke Einladungen an Menschen, die bereits Members sind?

**Comment by staude** [comment]
Freundschaften haben nichts mit Gruppenzugehörigkeit zu tun.

**Comment by lehr-ruetsche** [comment]
Aber sie werden doch in der Gruppe angeboten? Naja, vielleicht lag das Problem daran, dass ich "mit mir selbst gearbeitet habe".

**Comment by staude** [comment]
Und du hast auch 2 verschiedene Benutzer bei github?!

Ja, da wo Benutzer aufgelistet werden, gibt es auch eine Möglichkeit jemanden eine Freundschaftsanfrage zu schicken. Es ist ja auch wahrscheinlicher das man sich mit jemanden aus einer Gruppe in der man ist "befreunden" will als das man in der LIster aller Mitglieder wahllos sich jemanden sucht. 

Was su siehst sind die Mitglieder der Gruppe, es es wird die angeboten einem oder mehreren davon eine Freunschaftsanfrage zu senden.

**Comment by lehrruetsche** [comment]
okay, ich bin mal wieder auf dem Schlauch gestanden! Ich habe Gruppenmitglieder mit Freunden verwechselt.
