### ISSUE TITLE
Die Aktivitätsmail hat Probleme mit den Umlauten - "ä"

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#11]
![](https://trello-attachments.s3.amazonaws.com/56273c6be3793603bc1cbceb/503x653/afd43d9ce4833b5d23d2eeb1f52046bc/am_21.10.2015_um_09_19_08_hochladen.png)

**Comment by staude** [comment]
Bitte schliessen wenn ok

**Comment by joerglohrer** [comment]
hab's übersetzt - erledigt!
