### ISSUE TITLE
Worddokumente ins Doc verschieben

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#110]
Also, ich habe das mal ausprobiert, was Joachim uns heute Morgen erklärt hat: Ich habe in meiner Gruppe Philosophie ein Dokument aus dem Anhang in das doc - Feld verschoben.
Als ich es dann aufrufen wollte ging das aber nicht, sondern ich landete im Activity-Stream aller docs.
Das Word-Dokument, das ich in einen Fließtext im Schreibfeld verschoben hatte, öffnete sich dort NICHT.  Es ließ sich weiterhin nur im Anhang aufrufen.

**Comment by joerglohrer** [comment]
Und wo ist das Doc? URL?

**Comment by lehrruetsche** [comment]
Naja, das Schreibfeld oben, oberhalb des Anhangfeldes. Wie nennt sich das? Es ist doch das Schreibfeld, das sich öffnet, wenn man docs anklickt.

**Comment by joerglohrer** [comment]
Hattest du erwartet, dass sich das Worddokument in dem Doc-Dokument öffnet?
Das würde nämlich nicht gehen. Denn ein Worddokument braucht nach wie vor einen Computer auf dem Microsoft Word installiert ist.

**Comment by lehr-ruetsche** [comment]
Welchen Sinn macht es dann, ein Worddokument (Anhang) dorthin zu verschieben? Ich habe natürlich gedacht, dass es sich öffnen lässt. Auch im Anhang braucht es einen Computer, auf dem Microsoft Word installiert ist.

**Comment by joerglohrer** [comment]
Der Sinn wäre, dass man im Doc die Worddokumente (und andere Anhänge) auflisten und verlinken kann. In selbstgewählter Reihenfolge und Anordnung.
