### ISSUE TITLE
rechte Maustaste

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#111]
Ich bearbeite gerade einen Beitrag auf unserer Newsseite. Da klappt das Einfügen eines Textes mit der rechten Maustaste ganz problemlos. Nur auf der Gruppenseite nicht?

**Comment by joerglohrer** [comment]
Auf der Gruppenseite klappt es auch. Bei mir in Chrome und Firefox getestet.

**Comment by staude** [comment]
Ist doch aktuell oder kann das geschlossen werden? Wenn noch aktuell, bitte genaue URL, Nennung des Feldes und welcher Browser.
