### ISSUE TITLE
Bildquelle

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#115]
Wenn man einen Wordpress-Artikel für die Newsseite erstellt und rechts unten auf Beitragsbild festlegen geht, kann man bei diesem Beitragsbild keine Quellenangabe machen. Bei Bildunterschrift und Bildbeschreibung kann man zwar was reinschreiben, aber zumindest bei mir erscheint es nicht unter dem Bild - ich habe es mit verschiedenen Browsern probiert.

**Comment by johappel** [comment]
Bis wir dafür eine Lösung haben, muss die Bildquelle im Text erwähnt werden.

**Comment by johappel** [comment]
Durch die installation eines Plugins, werden nun die Bildquellen auch für Beitragsbilder angezeigt:
https://github.com/rpi-virtuell/reliwerk/wiki/isc
