### ISSUE TITLE
"Gruppe verlassen"

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#117]
Nun ist genau das passiert, was ich immer befürchtet habe: das riesige "Gruppe verlassen" - Schild verführt einfach dazu, darauf zu klicken, wenn man die Arbeit in der Gruppe beendet hat. Warum diese Aufforderung zum endgültigen Verlassen so groß da stehen muss, erschließt sich mir nicht. Kann man das nicht klein oben rein machen? Es ist wirklich irritierend. Heute Morgen habe ich mit Müh und Not eine Kollegin in die  Gruppe "geschleußt" und jetzt ist sie wieder draußen. Ich bitte sehr darum, diesen Button zu ändern.

**Comment by staude** [comment]
Meinst du wirklich das die Größe das Problem ist? Die Buttons an der Stelle sind alle so groß. 
Oder hilft es wenn wir die Übersetzung ändern, z.b. in "Mitgliedschaft beenden" oder so etwas in der Art?
Das Gruppe verlassen ein assoziation zu Logout / abmelden bei Nutzern hervorruft kann ich schon nachvollziehen.

**Comment by lehr-ruetsche** [comment]
Mitgliedschaft beenden fände ich eine gute Alternative! Liebe Grüße Andrea 

----- Ursprüngliche Nachricht -----
Von: "Frank Staude" notifications@github.com
Gesendet: ‎08.‎04.‎2016 09:27
An: "rpi-virtuell/reliwerk" reliwerk@noreply.github.com
Betreff: Re: [rpi-virtuell/reliwerk] "Gruppe verlassen" (#117)

Meinst du wirklich das die Größe das Problem ist? Die Buttons an der Stelle sind alle so groß. 
Oder hilft es wenn wir die Übersetzung ändern, z.b. in "Mitgliedschaft beenden" oder so etwas in der Art?
Das Gruppe verlassen ein assoziation zu Logout / abmelden bei Nutzern hervorruft kann ich schon nachvollziehen.

---

**Comment by lehrruetsche** [comment]
Bitte das mit dem "Mitgliedschaft beenden" bitte bald machen. Gerhard Ziener hat sich beschwert, dass er dauernd aus der Gruppe rausfliegt und ich vermute mal, dass er auch "Gruppe verlassen" angeklickt hat.

**Comment by johappel** [comment]
Lösungsverschlag: Gruppe verlassen Knopf in der Gruppenseite ausblenden

**Comment by staude** [comment]
Behoben in https://github.com/rpi-virtuell/rw-social-learner/releases/tag/1.1.8

**Comment by staude** [comment]
Gruppe verlassen Button ist wieder da.

**Comment by staude** [comment]
in 1.2.7 des social learners themes behoben
