### ISSUE TITLE
Altes rpi-virtuell - Problem mit gelöschten Seiten

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#119]
Es gibt Verlinkungen, deren Material nicht mehr vorhanden ist. Der Link wird aber nicht als fehlerhaft 404 angezeigt, sondern man landet auf der Startseite der Seite, auf der das Material war. Lässt sich das irgendwie feststellen, ob das Material wirklich noch verlinkt ist oder ob der Link woanders landet? (Habe mit Bernd Ost bereits darüber gesprochen).

**Comment by johappel** [comment]
Wenn die Seite umleitet auf die Startseite, verstösst dies eigentlich gegen die Regelen einer guten Datenhaltung, weil weder technisch noch manuell feststellbar ist, was mit dem ursprünglichen Material passeirt ist.
