### ISSUE TITLE
Passwort anfordern verwirrend

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#12]
Problem von Andrea: Ich musste mal wieder ein neues Passwort für mein "Alter Ego" anfordern. Es funktioniert sofort, aber das Feld, dass da eröffnet wird, ist total verwirrend!!! Ich habs auf jeden Fall nicht verstanden. Leider habe ich keinen Screenshot gemacht, sonst könnte ich erklären, was verwirrend war. Auf jeden Fall war meine Angst, jetzt wieder alles falsch zu machen und wieder von vorn anfangen zu müssen, ziemlich groß.

**Comment by johappel** [comment]
Mit Andrea klären

**Comment by johappel** [comment]
Andrea, kannst du noch einmal nachschauen, ob das Problem für dich noch existiert und ggf. das Problem an einem Screenshot erläutern?

**Comment by lehrruetsche** [comment]
Lieber Joachim, ich habe das Ganze nochmals durchgespielt mit einem Testnamen vom Kirchentag her, den ich ja nicht mehr dringend brauche. Und einen Screenshot gemacht.
Auch wenn ich es jetzt ansehe, finde ich es immer noch verwirrend. Es wird mir ein neues Passwort geschickt. Normalerweise müsste ich dies einsetzen und könnte es zu einem späteren Zeitpunkt in ein besser merkbares Passwort umwandeln. Hier habe ich mich gefragt: soll ich das neue zugeschickte Passwort oben einsetzen? Oder soll ich dort ein eigenes eingeben? Und wenn ich auf "zurücksetzen" gehe, was passiert dann? Welches Passwort wird gelöscht? Kannst Du meine Verwirrung nachvollziehen?
![neues passwort](https://cloud.githubusercontent.com/assets/15977289/11505687/fd817a0e-984b-11e5-9a3f-0306da8a2ffe.png)

**Comment by lehrruetsche** [comment]
Auch user2 ist übrigens in zwei Kursen, wenn diese Kurse allen angeboten werden sollten, könnte man dies anders ausdrücken: Kursangebot für alle Besucher zum Beispiel, nicht " you are registered in two courses" . Oder verstehe ich da etwas falsch?

**Comment by johappel** [comment]
#32 
Andrea meint, dass es kein Feld gibt, wo man ein neues Passwort eintragen kann. Ihr screenshot zeigt es aber anders. Siehe oben.

Oder hat sich etwas geändert?
