### ISSUE TITLE
Docs nicht löschbar

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#120]
![image](https://cloud.githubusercontent.com/assets/1091954/14818173/d3876c34-0bbb-11e6-8336-333be807ccf4.png)

**Comment by johappel** [comment]
![2016-05-06_16h16_26](https://cloud.githubusercontent.com/assets/307023/15075691/0e9a41b0-13a6-11e6-9f74-dfa571167e60.png)

Wird in der kommenden Version https://github.com/rpi-virtuell/rw-social-learner 1.1.2  gefixed.
