### ISSUE TITLE
Gruppenbild lässt sich nicht hochladen / kein Dialogfenster

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#121]
![image](https://cloud.githubusercontent.com/assets/1091954/14818198/13010d52-0bbc-11e6-9e75-5ea87a9adc55.png)

**Comment by joerglohrer** [comment]
Auch problematisch bei EAEW und da brauchen wir das dringend:
![image](https://cloud.githubusercontent.com/assets/1091954/14827186/703cdd46-0be1-11e6-9bee-2b7b32ba4c9e.png)

**Comment by joerglohrer** [comment]
Die updates sind durchgelaufen - Titelbilder für die Gruppen können immer noch nicht erstellt werden. :-(

**Comment by johappel** [comment]
Scheint am child theme zu liegen

**Comment by johappel** [comment]
fixed in rw-social-learner 1.1.0

**Comment by joerglohrer** [comment]
wie ich sehe läuft social-learner 1.1.0 schon auf gruppen.rpi-virtuell.de - was muss getan werden, damit es auch auf gruppen.eaew-online.de aktualisiert?
