### ISSUE TITLE
Gruppenadmin kann die Hierarchie nicht sehen

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#122]
![image](https://cloud.githubusercontent.com/assets/1091954/14827131/3c98e818-0be1-11e6-870a-40271ee700e2.png)
Nur der Site-Admin bekommt die Gruppenhierarchie angezeigt.

**Comment by johappel** [comment]
Ist kein Bug, sondern eine sinnvolle Einschränkung
