### ISSUE TITLE
Userprofile sind nicht systemweit nutzbar

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#124]
Userprofile in „gruppen“ werden nicht im login.reliwerk und auch nicht in den Blogs übernommen: Beispiel: http://gruppen.rpi-virtuell.de/members/schulrat/
http://news.rpi-virtuell.de/wp-admin/user-edit.php?user_id=39&wp_http_referer=%2Fwp-admin%2Fusers.php%3Frole%3Dcontributor

https://login.reliwerk.de/wp-admin/user-edit.php?user_id=13937&wp_http_referer=%2Fwp-admin%2Fusers.php%3Fs%3Dschulrat%26action%3D-1%26new_role%26paged%3D1%26action2%3D-1%26new_role2

**Comment by joerglohrer** [comment]
Nicht erreichbar: http://news.rpi-virtuell.de/author/schulrat/

**Comment by staude** [comment]
@empeiria  Die Autorenseite gibt es erst, wenn der User einen Beitrag veröffentlicht hat.

**Comment by staude** [comment]
@empeiria für erweiterte Profiledaten von BuddyPress zu einer anderen BuddyPress installation gibt es ein anderes Plugin. An den Loginserver wird eigentlich nichts zurückgemeldet aus den Profilen. Jedenfalls war das ursprünglich so festgelegt - eigentlich sollen die User auch nichts auf dem Loginserver machen, ausser Passwort ändern.

**Comment by joerglohrer** [comment]
@staude ok - Nach Veröffentlichung läuft das jetzt: http://news.rpi-virtuell.de/author/schulrat/ - Allerdings kann man auf reliwerk ja das Profil nicht editieren - Die User müssten folglich auf jeder Instanz ein extra Profil (Profilbild, Biografie, ...) erstellen, pflegen und aktualisieren.

**Comment by staude** [comment]
@empeiria Wenn auf den "anderen" System das distributed-profile-client Plugin installiert ist, wird beim erste login die Profildaten des User vom Profile-Server kopert. Aber nur einmalig, da findet keine stete Synchronisation statt. Was ja auch Sinnvoll ist, auf unterschiedlichen Server will ich ja evt auch durchaus unterschiedliche Texte in Profilfeldern haben. Sonst müssen wir zusammen mit @johappel das noch mal besprechen.

**Comment by joerglohrer** [comment]
Wo finde und wie installiere ich das "distributed-profile-client Plugin" z.B. auf http://news.rpi-virtuell.de/wp-admin/plugins.php ? @staude

**Comment by staude** [comment]
@empeiria  am einfachsten via github updater von https://github.com/rpi-virtuell/rw-distributed-profile-client

Der einzutragende Endpoint ist dann; http://gruppen.rpi-virtuell.de/rw_profile/ , wenn der Endpoint nicht schon  via wp-config vorgegeben ist
