### ISSUE TITLE
oEmbeds in den Gruppen laufen nicht mehr

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#127]
![image](https://cloud.githubusercontent.com/assets/1091954/15814808/3dfa1918-2bc9-11e6-9b80-b3c6fcc9d5c2.png)

**Comment by staude** [comment]
@empeiria  Geht nur wenn der Link ein einer neuen Zeile ist: Siehe http://gruppen.rpi-virtuell.de/groups/frank-testgruppe/
Bin mir gerade nicht sicher ob das vorher anders war.

**Comment by johappel** [comment]
war m.W. immer so. BTW.: das Verhalten ist zumindest völlig identisch mit den den normalen Beiträgen. 
http://standalone.reliwerk.de/2016/06/06/test/

**Comment by joerglohrer** [comment]
ok. Danke! Dann mache ich ein Tutorial dazu.
