### ISSUE TITLE
Artikel speichern als Gruppenmitglied in Firefox

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#130]
In der Rolle "Gruppenmitglied" öffnet sich nach dem Klick auf "Speichern" eines Artikels dieses Fenster und es wird **NICHT** gespeichert:
![image](https://cloud.githubusercontent.com/assets/1091954/16768630/5c1b00c2-4845-11e6-8b9e-97abc2c67907.png)
In Chrome klappt das Speichern problemlos

**Comment by joerglohrer** [comment]
Mit der Gruppenrolle "Administration" klappt das Speichern in Firefox. Lediglich als Gruppenmitglied kommt es zur Fehlermeldung.

**Comment by johappel** [comment]
fixed in Social Learner 1.1.7
