### ISSUE TITLE
LearnDash Übersetzungsproblem(e)

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#131]
Es gibt im Learndash-Kursmodul seltsame Wortschöpfungen, die ich mit dem Loco-Translator nicht in den Griff bekomme (gesuchte Worte kommen nicht vor). 
ZB: "TestsStatus": Dort stand früher einmal "Test", sollte aber in "Quiz" geändert werden.
Oder "Kurs Discussion": Dort könnte zB "Kurs-Diskussion" oder "Diskussion in der Kursgruppe" stehen, aber das Wort "Discussion" sucht man im Loco-Wörterbuch vergeblich.

![image](https://cloud.githubusercontent.com/assets/16247643/17130036/ca1cfc70-5316-11e6-96c2-7d8cb1b87331.png)

Kann es sein, dass ein Kursmodul noch nicht im Loco Translator noch nicht vorkommt?

**Comment by staude** [comment]
Große Teile kommen auch aus dem Plugin  "Boss for LearnDash" 
Habe ein paar der offensichtlichsten Stellen schon man angefasst.

Wenn du weitere Stellen hast die du nicht findest, noch mal melden.
Ist leider nicht immer ganz klar von welchem Plugin oder Theme an einer Stelle eine Übersetzung kommt.
