### ISSUE TITLE
Revisionen von Docs in Chrome nicht auswählbar

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#136]
Auf dem Mac links Chrome - rechts Firefox:
![image](https://cloud.githubusercontent.com/assets/1091954/18576285/6dd6f374-7be0-11e6-834f-9f81279e141e.png)

**Comment by johappel** [comment]
Nachvollziebar..

**Comment by staude** [comment]
Problem in Chrome 60.0 nicht mehr reproduzierbar.
