### ISSUE TITLE
Artikel ändern sich in den Rechten!

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#137]
Ein Artikel, der in einer GRuppe vom Admin (Mir) erstellt wurde wird von einem Gruppenmitglied bearbeitet.
Dadurch verliert der Artikel die Gruppenzugehörigkeit und KEIN Gruppenmitglied kann ihn mehr bearbeiten.
Im aktuellen Beispiel bearbeitet Rainer Zwenger den Artikel http://gruppen.rpi-virtuell.de/docs/argumente-fuer-den-ru-in-der-schule/ 
und hat anschließend nur noch Leserechte: 
![image](https://cloud.githubusercontent.com/assets/1091954/18707127/fe13eeca-7ff4-11e6-8021-0874910925fe.png)

**Comment by johappel** [comment]
Ich kann den beschriebenen Fehler zumindest in Testgruppen und mit einem Testbenutzer nicht nachstellen. Denkbar wäre ja auch eine unabsichtliche Änderung der der Rechte durch den Nutzer. Konntest du den Fehler nachvollziehen? 

Wenn ja brauche ich
- den Gruppennamen
- den benutzten Browser
- die ungefähre Bearbeitungszeit, bevor das Doc gespeichert wurde

**Comment by johappel** [comment]
Es handelt sich nicht wirklich um ein Bug sondern um eine ungewollte Einstellung in der Gruppenadministration.

![image](https://cloud.githubusercontent.com/assets/307023/18710241/704dd032-8004-11e6-9a67-861f3e9d3fb9.png)

Allerdings ist das Verhalten insofern trotzdem überraschend, weil man davon ausgeht, dass einmal verknüpfte Docs mit der bestehenden Verknüpfung auch weiterhin gespeichert werden sollten.

@empeiria Kannst du das Problem in https://github.com/boonebgorges/buddypress-docs schildern?

**Comment by lehr-ruetsche** [comment]
In einer meiner Gruppen ist das gleiche passiert, ohne jede Konsequenzen… Ich habe etwas angefangen, jemand anders hat es weiter gemacht… Alles gut.

Von: Jörg Lohrer [mailto:notifications@github.com] 
Gesendet: Mittwoch, 21. September 2016 12:16
An: rpi-virtuell/reliwerk
Betreff: [rpi-virtuell/reliwerk] Artikel ändern sich in den Rechten! (#137)

Ein Artikel, der in einer GRuppe vom Admin (Mir) erstellt wurde wird von einem Gruppenmitglied bearbeitet.
Dadurch verliert der Artikel die Gruppenzugehörigkeit und KEIN Gruppenmitglied kann ihn mehr bearbeiten.
Im aktuellen Beispiel bearbeitet Rainer Zwenger den Artikel http://gruppen.rpi-virtuell.de/docs/argumente-fuer-den-ru-in-der-schule/ 
und hat anschließend nur noch Leserechte: 
 https://cloud.githubusercontent.com/assets/1091954/18707127/fe13eeca-7ff4-11e6-8021-0874910925fe.png image

**Comment by joerglohrer** [comment]
War das Problem jetzt, dass Artikel bei der Gruppeneinstellung eventuell nicht aktiviert war?

**Comment by johappel** [comment]
Das Problem war die Einstellung, dass nur Gruppenadministratoren Dokumente mit der Gruppe verknüpfen durften. Ich habe es korrigiert:

![image](https://cloud.githubusercontent.com/assets/307023/18710337/09d12f60-8005-11e6-9332-78edecafeb7b.png)
