### ISSUE TITLE
Nutzer haben nur eine Reihe Werkzeuge im Editor

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#138]
Normale Nutzer haben nur eine Zeile Werkzeuge:
![image](https://cloud.githubusercontent.com/assets/1091954/18711932/6d4cccdc-800c-11e6-8f4e-c3ce7dc642f7.png)
Wohingegen bei mir als Admin zwei erscheinen:
![image](https://cloud.githubusercontent.com/assets/1091954/18711962/8fc61cfa-800c-11e6-80ec-0ba7310fd62c.png)

**Comment by joerglohrer** [comment]
Liegt das an den Einstellungen von TinyMCE?
http://gruppen.rpi-virtuell.de/wp-admin/options-general.php?page=tinymce-advanced

**Comment by staude** [comment]
Die zusätzlichen Zeilen kommen vom TinyMCE advanced. Aber imho gibt es da keine Begrenzung auf Userrollen

**Comment by joerglohrer** [comment]
Die aktuellste Version wäre 4.4.3 
https://www.tinymce.com/docs/changelog/#version443-september12016
Wir haben nur 4.4.1.
Eventuell löst auch ein update das Problem?
