### ISSUE TITLE
Tabellen im WYSIWYG-Editor nicht nutzbar

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#139]
![image](https://cloud.githubusercontent.com/assets/1091954/19115576/d697fc46-8b12-11e6-84da-8e0fd6c0c56e.png)
zugehörige Support-Anfrage:
http://support.rpi-virtuell.de/scp/tickets.php?id=50

**Comment by johappel** [comment]
Im Backend muss unter Advanced Tiny-MCE die Opton für Front-End aktiviert sein
