### ISSUE TITLE
Gruppenmitglieder werden inkonsistent angezeigt:

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#141]
Die Gruppe http://gruppen.rpi-virtuell.de/groups/die-onliner/ hat aktuell 5 Mitglieder.
Jedoch werden bei mir 34 angezeigt:
![image](https://cloud.githubusercontent.com/assets/1091954/19491162/334c2782-9572-11e6-9c6b-fbe20131beac.png)
und bei Christian Günther 10:
![image](http://gruppen.rpi-virtuell.de/wp-content/uploads/2016/10/membernumber-scsh.jpg)

**Comment by johappel** [comment]
Ich kann es für den Moment nicht nachvollziehen. Was muss ich tun, damit der Bug bei mir auch auftritt?
![image](https://cloud.githubusercontent.com/assets/307023/19505500/333a5182-95c3-11e6-9d35-57abe820aea4.png)
