### ISSUE TITLE
Autoren -> Institutionen -> Landeskirchen?

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#142]
Der Eintrag von:
http://material.rpi-virtuell.de/organisation/religionspaedagogisches-zentrum-heilsbronn/
bringt mich auf die Idee, dass hier evtl. noch die Evangelisch-Lutherische Kirche in Bayern erfasst werden sollte. 
Also noch Landeskirchen und Bistümer als Taxonomie einführen?

**Comment by staude** [comment]
Materialpool Issues bitte https://github.com/rpi-virtuell/rw-materialpool/issues eintragen

**Comment by joerglohrer** [comment]
ok .geschlossen und hier neu eröffnet: https://github.com/rpi-virtuell/rw-materialpool/issues/58
