### ISSUE TITLE
Dr. Titel

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#143]
![image](https://cloud.githubusercontent.com/assets/1091954/20521587/28ad349c-b0ac-11e6-81dc-b8b1938b9543.png)
Eigentlich trägt http://material.rpi-virtuell.de/autor/ute-baierlein/ den Doktortitel.
Dafür haben wir kein Feld zum Eintragen bislang

**Comment by staude** [comment]
Materialpool Issues bitte https://github.com/rpi-virtuell/rw-materialpool/issues eintragen

**Comment by joerglohrer** [comment]
Ok. Hier geschlossen und neu eröffnet unter: https://github.com/rpi-virtuell/rw-materialpool/issues/57
