### ISSUE TITLE
Schlagworteingabe stockt noch

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#144]
![image](https://cloud.githubusercontent.com/assets/1091954/20521883/a9cfc14c-b0ad-11e6-9b83-7c7bd538d7e8.png)
Ich musste für die Eingabe von jedem NEUEN Schlagwort den Artikel zuerst aktualisieren.
Irgendwie scheint sich dadurch das Schlagwort neu anzulegen und ist erst DANACH zur Eingabe verfügbar

**Comment by staude** [comment]
a: Du kannst ein neues Schlagwirt direkt im Material eingeben und mit Return wird das dann gespeichert.

b: Pods macht da kein Ajax sondern hat die Elemente schon in der Seite, daher taucht auch ein auf einem anderen Tab hinzugefügtes Schlagwort da auch nicht nachträglich auf.

**Comment by staude** [comment]
Muss ggf später mal auf Ajax umgestellt werden wenn die Listen zu lang werden.

**Comment by staude** [comment]
Materialpool Issues bitte https://github.com/rpi-virtuell/rw-materialpool/issues eintragen
