### ISSUE TITLE
buddypress Beitrag erzeugt Medienkopie 

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#145]
Die Activity http://gruppen.rpi-virtuell.de/members/joerglohrer/activity/6711/ erzeugt den Upload:
http://gruppen.rpi-virtuell.de/wp-content/uploads/2016/11/20160812_135252.jpg
Ist das nicht 
1. urheberrechtlich problematisch, wenn das Eingeben von Links in Buddypress automatisch Media-Uploads in der WordPress-Instanz gruppen erzeugt?
2. vom Datenvolumen her problematisch, wenn hier mit Aktivitäten im Gruppen-Stream die Medienübersicht automatisiert wächst?

**Comment by johappel** [comment]
Das wusste ich nicht, aber das macht das boss.theme. Wenn wir das ändern wollen, erfordert das einen weiteren weitreichenden Eingriff. Wie sollen wir damit umgehen?

**Comment by staude** [comment]
Tippe mal auf die BuddyBoss Wall, die Bilder von Remoteadressen holt.

**Comment by johappel** [comment]
Ude Maisen sieht darin kein Problem
