### ISSUE TITLE
Gruppe beitreten ist sehr umständlich

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#147]
Um einer Gruppe beizutreten gibt es eigentlich nur die Möglichkeit der Gruppensuche und dann auch nur für angemeldete Nutzer.
Der Link zur Gruppe führt zu keiner Beitrittsmöglichkeit:
http://gruppen.rpi-virtuell.de/groups/buchmalerei-klosterinsel-reichenau/
ergibt für **unangemeldete** User:
![image](https://cloud.githubusercontent.com/assets/1091954/20620067/1c46bfa4-b2f8-11e6-803e-a4e572fba4e8.png)
für **angemeldete** User:
![image](https://cloud.githubusercontent.com/assets/1091954/20620062/0e271004-b2f8-11e6-9c5d-b90f42fabd32.png)

Einzig eine Suche ermöglicht den Beitritt
http://gruppen.rpi-virtuell.de/groups/?s=Klosterinsel&groups_search_submit=Suchen
Allerdings nur für angemeldete User:
![image](https://cloud.githubusercontent.com/assets/1091954/20619793/b4f9608c-b2f6-11e6-8501-0692a9570f69.png)
Für unangemeldete User gibt es gar keine Möglichkeit, beizutreten und sich dabei anzumelden.

Wie sollen Leute, die z.B. in einem Blogartikel für die Gruppe werben, Leuten ermöglichen dort beizutreten?
(Beispiel: http://news.rpi-virtuell.de/2016/11/23/adventskalender-reichenau/ - hier gelöst mit Suchanfrage als Hyperlink)

**Comment by staude** [comment]
Hab mal rumgefragt ob jemand was kennt.

**Comment by johappel** [comment]
gelöst:

![image](https://cloud.githubusercontent.com/assets/307023/21593198/bfc765d6-d114-11e6-848b-640506a6fe12.png)
