### ISSUE TITLE
Lizenzen bei den Bildern

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#148]
Die Möglichkeit, bei den einzutragenden Bildern anzugeben, ist sehr begrenzt. Es wird nur 2.0 angeboten.

**Comment by staude** [comment]
Da sind weitere eingetragen

![2017-08-18_1207](https://user-images.githubusercontent.com/870951/29454551-e007b20e-840d-11e7-9ac3-925106fd5624.png)


Weitere Lizenzen können auf der Einstellungsseite des Plugins ( https://news.rpi-virtuell.de/wp-admin/options-general.php?page=isc_settings_page ) hinzugefügt werden.

![2017-08-18_1206](https://user-images.githubusercontent.com/870951/29454509-c56f2670-840d-11e7-8195-0fcdf02efa6d.png)
