### ISSUE TITLE
Nachrichten Hervorheben statt Markieren

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#15]
Bei "Nachrichten" taucht der Begriff "Markieren" links im Menü auf. Rechts im Feld bedeutet er aber etwas anderes. Könnten man hier "Hervorheben" oder "Favorisieren" verwenden. Oder links im Menü auch "Mit einem Stern versehen" schreiben?

![](https://trello-attachments.s3.amazonaws.com/5641b47408e37749fbcff5f3/1920x1080/a2a5e2340f5856679142ec613975d359/Markieren.png)

**Comment by staude** [comment]
Vorschlag: Im Pulldown Ändern in "Als Gelesen/ungelesen  kennzeichnen"

Im Pulldown steht "Stern hinzufügen", im Infotext über den Stern rechts steht "Markieren ..."  das sollte vereinheitlicht werden. 
Ich wäre für "markieren", bei "Stern" erwarte ich entweder das es auch noch andere Symbole gibt oder das es was im Sinne von "liken" ist.

**Comment by johappel** [comment]
@beo9999 kümmerst du dich um die Übersetzung?

**Comment by beo9999** [comment]
OK, ich hab es jetzt im Dropdown-Menü mal in "Markieren / Markierung entfernen" geändert. Bei "Als gelesen / ungelesen ..." hab ich jetzt mal "markieren" gelassen, weil es noch einige andere Stellen gibt, wo es in dieser Kombination verwendet wird.

Bin aber nicht sicher, ob das sich dem Normaluser so sofort erschließt (allgemein die Logik hinter den Markierungen).
