### ISSUE TITLE
Wie kann man Bilder aus der Liste löschen?

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#150]
http://news.rpi-virtuell.de/wp-admin/media.php?attachment_id=18356&action=edit

Ich hätte gerne einen Tipp, wie ich hier ein Bild gelöscht kriege. Das Bild gibt es eigentlich nicht mehr. Ich habe ein komplett neues eingefügt und hätte das Bild gern gelöscht. Das kriege ich in der direkten Bildbearbeitung nicht hin und auch  nicht in der Bilderliste der Fehlenden Bildquellen.

**Comment by joerglohrer** [comment]
![image](https://user-images.githubusercontent.com/1091954/29822309-42fd14ce-8ccb-11e7-8f99-909234e8f9bf.png)
Bei mir kommt diese Meldung. 
Was meintest du, @lehr-ruetsche ?

**Comment by lehr-ruetsche** [comment]
Bei mir kommt auch diese Meldung. Vergessen wir das Ganze und warten, bis das Problem wieder auftaucht. Ich glaube, das Problem war, das das Bild bei fehlenden Quellen war und ich es ganz herausgenommen hatte, aber nichtlöschen konnte.
