### ISSUE TITLE
Nicht ausreichende Angaben

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#152]
Bei diesem Bild habe ich per Email die Erlaubnis erhalten, das Bild zu benutzen:

http://news.rpi-virtuell.de/2016/10/04/gott-und-die-welt-1-10-16-29-1-17/

allerdings mit genau vorgegebenen Angaben. Die kann ich in die Felder gar nicht so genau eintragen. Nun erscheint es doppelt.

**Comment by johappel** [comment]
Ich glaube es ist sinnvoll dein Nameskürzel bei den Angeben dazuzugeben
![image](https://cloud.githubusercontent.com/assets/307023/21008280/52c5ce82-bd41-11e6-85a8-cc4121a9c8d4.png)

Doppelt erscheint es weil du es sowohl unter den Text im Inhalt einträgst als auch bei den Angaben in den Medien

**Comment by lehr-ruetsche** [comment]
okay
