### ISSUE TITLE
Schwierige Gegenkontrolle

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#153]
Wenn ich in der Liste der fehlenden Bilder etwas aktualisiere ist es schwupps aus der Liste verschwunden und wenn ich mir den Beitrag ansehen will, der durch aus seltsam aussehen kann nach der Veränderung, ist es etwas mühselig, ihn zu finden.

**Comment by johappel** [comment]
wenn du untere Stream im Menü nachschaust, siehst du was du als letztes bearbeitet hast
![image](https://cloud.githubusercontent.com/assets/307023/21008386/cc9b9c14-bd41-11e6-9e9c-2f0d8280aafd.png)
