### ISSUE TITLE
Nicht löschbar

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#154]
Auch dieses wurde verbessert, zeigt aber immer noch das Alte an:

http://news.rpi-virtuell.de/wp-admin/media.php?attachment_id=17932&action=edit

Asisi

Und dieses

http://news.rpi-virtuell.de/wp-admin/media.php?attachment_id=17579&action=edit

Terra Max2

**Comment by johappel** [comment]
um welches der bilder geht es
![image](https://cloud.githubusercontent.com/assets/307023/21010244/4b8d4b72-bd4b-11e6-8d97-a8d4b3187d4f.png)

Welches soll gelöscht werden?

**Comment by lehr-ruetsche** [comment]
Die ersten beiden habe ich heute zugeschickt bekommen, das letzte ist das Plakat. WEnn man ein Bild nicht nur ergänzt mit Beschriftungen, sondern ein ganz neues einsetzt, dann ist diese Fehlermeldeliste ein Problem.

**Comment by johappel** [comment]
Ich versuche ja nur nachzuvoollziehen, wo der Fehler auftaucht: Soll ich jetzt versuchen, das Bild Asisi.jpg zu löschen, damit der Fehler auftritt?

**Comment by johappel** [comment]
Ich habe die Verbindung zu den Beiträgen gelöst und das Bild gelöscht. Es gab keinen Fehler.

**Comment by lehr-ruetsche** [comment]
Wie kannst du das löschen? Es sind mindestens noch vier Beiträge auf der Seite, die gelöscht werden müssen. Wie geht das?

Und woher weiß ich, dass die Beiträge überhaupt noch angezeigt werden. Ich kümmere mich hier zum Teil um terminlich veraltetes material.

 

 

Von: Joachim Happel [mailto:notifications@github.com] 
Gesendet: Donnerstag, 8. Dezember 2016 14:15
An: rpi-virtuell/reliwerk
Cc: lehr-ruetsche; Author
Betreff: Re: [rpi-virtuell/reliwerk] Nicht löschbar (#154)

 

Ich habe die Verbindung zu den Beiträgen gelöst und das Bild gelöscht. Es gab keinen Fehler.

**Comment by johappel** [comment]
Ist die Frage noch offen?
