### ISSUE TITLE
Konfiweb gelöscht - in der Liste immer noch da

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#155]
Konfiweb habe ich ganz gelöscht, als Beitrag. In der Liste erscheint es aber immer noch. Also in der Fehlende Quellen bei Bilder liste.

**Comment by lehr-ruetsche** [comment]
oh, mir ist das gute alte Delete wieder eingefallen! Das funktioniert ja wunderbar. Nö, doch nicht :-(

**Comment by johappel** [comment]
wo finde ich das?

**Comment by lehr-ruetsche** [comment]
Da ich jetzt weiß, wie ich löschen kann, habe ich es gelöscht J

So geht es jetzt echt etwas schneller.

Wobei die Suche nach den Bilddaten einfach Zeit kostet, ein anderes einfügen noch mehr.

 

 

Von: Joachim Happel [mailto:notifications@github.com] 
Gesendet: Donnerstag, 8. Dezember 2016 16:03
An: rpi-virtuell/reliwerk
Cc: lehr-ruetsche; Author
Betreff: Re: [rpi-virtuell/reliwerk] Konfiweb gelöscht - in der Liste immer noch da (#155)

 

wo finde ich das?
