### ISSUE TITLE
Kann "Zukunft der Arbeit" nicht finden und löschen

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#156]
Die beiden Einträge Zukunft der Arbeit kann ich leider nirgends finden und somit auch nicht löschen.
Es geht um die Themenwoche der ARD in diesem Jahr, das muss man ja nicht ewig online lassen, sondern könnte es einfach löschen. Nur finde ich sie nicht.

**Comment by staude** [comment]
Kann ich auch nicht finden. Wurde evtl schon gelöscht.
