### ISSUE TITLE
"Einverständnis"

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#159]
![img_6190](https://cloud.githubusercontent.com/assets/1091954/22106238/17fc2a9e-de48-11e6-840a-43b81deb4acc.PNG)

**Comment by lehr-ruetsche** [comment]
Lieber Jörg,


ich habe diese Email nicht ganz verstanden. Könntest du mir erklären, was du mir
mit dieser Email mitteilen wolltest?

Habe zurzeit eine noch längere Leitung als sonst.


Liebe Grüße

Andrea

**Comment by joerglohrer** [comment]
Da steht "Eiverständnis" statt "Einverständnis" - der issue geht an @johappel, weil ich nicht weiß wo man es ändern kann.
