### ISSUE TITLE
Artikel oder Docs?

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#162]
Im Gruppenbereich taucht wieder an mehreren Stellen der Begriff "Docs" auf:
![image](https://cloud.githubusercontent.com/assets/1091954/23762597/bb849046-04f6-11e7-9f7f-859f33c7b6d7.png)
Wir wollten eigentlich nur noch mit dem Begriff "Artikel" arbeiten, oder?

**Comment by staude** [comment]
Wenn die Docs aktualisiert werden müssen auch die Übersetzungen kontrolliert werden. Das war vollständig auf Artikel umgestellt von mir.

**Comment by staude** [comment]
mo/po scheinen korrekt zu sein. Also mal rausfinden wo der Test eigentlich herkommt.
