### ISSUE TITLE
Hyperlinks im Gruppenbereich kaum erkennbar

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#166]
Die Hyperlinks im neuen lila Theme von gruppen mit lila contra schwarz sind kaum erkennbar, da sich der Fliesstext (schwarz) wenig abhebt von den Links (dunkel-lila):
![image](https://cloud.githubusercontent.com/assets/1091954/25324639/2e97c960-28c7-11e7-8449-9f0b4612fa90.png)
evtl. blau oder helleres lila?

**Comment by staude** [comment]
Doppelt -> #174
