### ISSUE TITLE
Gruppen - Mail

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#168]
Emails von rpi-virtuell-Gruppen erscheinen im Postfach nur als "Gruppen" - da wird nicht deutlich, dass die Mail von rpi-virtuell sind. Sollte das eher "rpi-Gruppen" sein?
![image](https://cloud.githubusercontent.com/assets/1091954/25607862/cf5a9c4a-2f18-11e7-93b4-97e5bf235859.png)

**Comment by staude** [comment]
Die Mailvorlagen können im Backend unter E-Mails bearbeitet werden.
Den Sitenamen können wir nicht ändern, aber in den  Mailvorlagen kannst du statt dem sitenamen ja was anderes eintragen.
