### ISSUE TITLE
Gruppen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#169]
Wenn man einer Gruppe beitreten will und sich neu registrieren lässt, darf man beim Namen keine Großbuchstaben, keinen Punkt und keinen Bindestrich verwenden. Das wird aber nirgendwo erwähnt. Ich habe das prozedere heute mit eine Klasse gemacht, es hat eine halbe Stunde gedauert, weil der Capcha oft auch noch recht umständlich war. Und welcher von den beiden Namen, die man angeben soll, wird nachher angezeigt? Das ist auch nicht klar.
Außerdem sind die Informationen zu Gruppen wieder in Englisch und der schöne riesigie Button "Gruppe verlassen" ist auch wieder da.

**Comment by staude** [comment]
- [x] "Gruppe verlassen" innerhalb der Gruppe
- [ ] Hinweistext auf der Registrierungsseite zu Usernamen
- [ ] Hinweistext auf der Registrierungsseite, Name

**Comment by staude** [comment]
@lehrruetsche was meinst du mit 

> Außerdem sind die Informationen zu Gruppen wieder in Englisch

**Comment by lehr-ruetsche** [comment]
Frank, das ist jetzt ziemlich lange her. Irgendwas muss damals in Englisch gewesen sein. Aber wenn das jetzt kein Problem mehr ist und alle anderen Dinge geklärt sind, dann kann man diesen Issue auch schließen.
