### ISSUE TITLE
Foren Thema anlegen gelingt nicht

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#17]
Ich bin in meiner Testgruppe soweit gekommen, dass ich ein Forum gründen wollte. Allerdings gelang es mir nicht, ein Thema zu erstellen. (Andrea)

![](https://trello-attachments.s3.amazonaws.com/5641c640911278cd39c48da7/1920x1080/e70337e32305abeedba6ee4dcf885386/Thema_erstellen.png)

**Comment by staude** [comment]
Ein Thema muss auch einen Text haben und nicht nur einen Titel.
Dann konnte ich das Problemlos anlegen in meinem Testforum.
Die Fehlermeldung lautet in dem Fall ja auch "Das Thema darf nicht leer sein."-
