### ISSUE TITLE
Gruppenerstellung hakt.

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#171]
Nach dem zweiten Schritt "Einstellungen" geht's nicht weiter:
![image](https://cloud.githubusercontent.com/assets/1091954/25705440/98998b00-30dd-11e7-818a-820efc96ff92.png)
Die Gruppe wird trotzdem angelegt:
![image](https://cloud.githubusercontent.com/assets/1091954/25705462/a6b340a0-30dd-11e7-8c31-591b4f9f6663.png)
und kann als Workaround hier in den Einstellungen fertig konfiguriert werden.

**Comment by staude** [comment]
Workaround: BuddyPress auf 2.7.5 downgraden (geht mit dem Plugin WP Rollback auch in der Pluginverwaltung im Backend) oder Groups Hierarchy deaktivieren - das beisst sich mit BuddyPress 2.8.x

**Comment by joerglohrer** [comment]
Jetzt auch auf gruppen.rpi-virtuell -> Gerade 2 von 3 Seelsorge-Gruppen gelöscht, weil das PTI Bonn mehrfach angelegt hat. Bekommen wir das in den Griff?
