### ISSUE TITLE
Support-Bereich Hintergrundgrafik

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#175]
In http://support.rpi-virtuell.de/ erscheint das OSTicket Känguru und die Orangefarben im Hintergrund. Sollten wir da unseren Tintenklecks oder das Vierfarben-Design im Hintergrund einblenden?
![image](https://cloud.githubusercontent.com/assets/1091954/26818792/60d207c8-4a9c-11e7-9923-e6c9db5fbf06.png)

**Comment by johappel** [comment]
Bei mir sieht die Seite ganz anders aus:

![image](https://cloud.githubusercontent.com/assets/307023/26820472/3b3d9c1e-4aa3-11e7-8968-26315375a539.png)

**Comment by johappel** [comment]
ah habs gefunden: http://support.rpi-virtuell.de/scp/login.php

diese Seite sehen aber nur admins und keine User

**Comment by johappel** [comment]
Hab die aber den Klecks trotzdem reingebaut :-)
