### ISSUE TITLE
h5p-Einbettung in Artikeln

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#176]
Ich habe hier im Artikel sowohl mit iframe als auch mit script versucht h5p-Inhalte einzubetten, was nicht geklappt hat.
Als einziger Trick bleibt ein Screenshot mit Link, der dann das Original im Blog öffnet:
https://gruppen.rpi-virtuell.de/docs/h5p-test/

**Comment by staude** [comment]
http://blogs.rpi-virtuell.de/h5pdev/wp-admin/admin-ajax.php?action=h5p_embed&id=2 liefert auch nur FU statt irgendwie den Content. Bist du sicher das das Multisitetauglich ist?

**Comment by joerglohrer** [comment]
http://blogs.rpi-virtuell.de/h5pdev/wp-admin/admin-ajax.php?action=h5p_embed&id=2  öffnet im fullscreen solagge ich angemeldet bin:
![image](https://user-images.githubusercontent.com/1091954/28120200-9d4d3384-6717-11e7-8453-1d0ad730aeac.png)

**Comment by joerglohrer** [comment]
Hat auch nix mit h5p zu tun - FU kommt auch für Autoren, wenn neuer Beitrag erstellt werden will:
![image](https://user-images.githubusercontent.com/1091954/28120404-4068ea9a-6718-11e7-841d-dda1efb1cc57.png)

**Comment by staude** [comment]
>FU kommt auch für Autoren, wenn neuer Beitrag erstellt werden will:

Wobei genau

**Comment by joerglohrer** [comment]
Es ist weitreichender und scheint ein Rechteproblem zu sein: 
http://www.youtube.com/watch?v=clZDKnnzlHA
Wobei die "FU"-Geschichte erstmal nix mit der Einbettung von H5P in Artikeln zu tun hat.

**Comment by staude** [comment]
FU kommt von https://github.com/rpi-virtuell/rw-blog-wizard, einbetten http vs https hatten wir besprochen. daher close.
