### ISSUE TITLE
Artikel in Gruppen heissen wieder Docs

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#177]
![image](https://user-images.githubusercontent.com/1091954/28119578-9cceacaa-6715-11e7-852b-b0627ed04957.png)

**Comment by staude** [comment]
in /home/rpi-virtuell/public/gruppen/wp-content/languages/plugins 
buddypress-docs-de_DE.po / mo in   bp-docs-de_DE.po / mo umbenannt
