### ISSUE TITLE
rpi-virtuell.net - Kasten aktualisieren

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#179]
![image](https://user-images.githubusercontent.com/1091954/28127729-db038dc0-672d-11e7-9c9c-1af7904b33c9.png)
... sind wir stolz, das**s, wir** das neue rpi-virtuell vorstellen **(zu)** können. 
... nicht mehr als Pla**tt**form sondern als Soziales Netzwerk ...

**Comment by joerglohrer** [comment]
Korrekturen oben **fett**

**Comment by staude** [comment]
Für das alte System hab ich keinen Zugang und auch keine Infos was wo zu finden ist.

**Comment by staude** [comment]
ping @johappel

**Comment by johappel** [comment]
done
