### ISSUE TITLE
Blogfeed in Gruppen bringt Userbild

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#180]
In der Gruppe 
https://gruppen.rpi-virtuell.de/groups/h5pdev/
wird der RSS-Feed des assoziierten Blogs 
http://blogs.rpi-virtuell.de/h5pdev
in den Aktivitäten ein Profilbild
![image](https://user-images.githubusercontent.com/1091954/28303218-39fef928-6b92-11e7-867a-c076f87ace1e.png)
So wie es aussieht, ist das das von Marion Holzhüter https://gruppen.rpi-virtuell.de/members/marion/
Sie ist allerdings weder in der Gruppe noch im Blog.
Ist das standardmässig das Bild für Feeds in den Aktivitäten?

**Comment by staude** [comment]
gefixt mit https://github.com/rpi-virtuell/rw-social-learner/commit/66bd7153d95ae6a9e888bd749941e3a8e5605efc
