### ISSUE TITLE
Frage einreichen führt nicht zur Anmeldung

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#181]
![image](https://user-images.githubusercontent.com/1091954/28567621-2c7dfcb2-7133-11e7-9533-22ccba0f9b12.png)
Wenn man unangemeldet auf http://fragen.rpi-virtuell.de/ eine Frage stellen will, kommt man auf diese Seite: 
http://fragen.rpi-virtuell.de/add-question/
Hier geht's mit "[anmelden](http://fragen.rpi-virtuell.de/my-account/)" nicht weiter

**Comment by staude** [comment]
lade es mit gerade zum lokal installieren runter.

**Comment by staude** [comment]
Fehler in den Fragen Plugin, in der template-myaccount.php 

Sehe aber keine Möglichkeit das von extern zu ändern. Kein Hook und keine Möglichkeit das Template innerhalb des Themes zu überschreiben (man ist das schlecht programmiert)

noch mal drüber schlafen und morgen in ruhe noch mal drüber schauen

**Comment by joerglohrer** [comment]
Solange noch wenig Inhalte da sind, könnte man auch auf ein anderes Q&A umsteigen...

**Comment by staude** [comment]
anderes plugin ist im test
