### ISSUE TITLE
Whitespace in der Mobilansicht - Gruppen  

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#183]
![img_8744](https://user-images.githubusercontent.com/1091954/28743173-9d49210c-7443-11e7-957b-55ab40947c98.PNG)

**Comment by johappel** [comment]
fixed in https://github.com/rpi-virtuell/rw-multiinstanz-navigation/commit/0c715d3afe5051534a1b6a706603f2b13d71208d

**Comment by joerglohrer** [comment]
super! 
Bleibt noch ein whitespace am Ende der Navigation:
![image](https://user-images.githubusercontent.com/1091954/28768421-d338af9a-75d7-11e7-99f1-996b20f4ec28.png)

**Comment by johappel** [comment]
Das ist eigentlich kein Whitespace, das untere ist die sitebar. Keine Ahnung, ob man die auf volle Breite setzen sollte bei jedem Mobilgerät
