### ISSUE TITLE
Bilder auf Gruppen Startseite

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/reliwerk#186]
Weil ich gerade "insecure Contents" am fixen war, gesehen das Bilder auf der Gruppen Startseite  direkt von www.edmodo.com/ geladen werden.  Sind das CC Bilder?

**Comment by johappel** [comment]
Die Startseite sollte insgesamt überarbeitet und dynamischer werden

**Comment by joerglohrer** [comment]
Die Bilder habe ich ersetzt. Die Startseite insgesamt sollten wir mit dem Designer besprechen.
