### ISSUE TITLE
Wenn man auf eine Gruppe klickt, in der man nicht Mitglied ist kommt eine Weiterleitungsschleife

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#19]
![](https://trello-attachments.s3.amazonaws.com/56444c744b05ea43c006d714/1287x351/3a12c2921531fe9f2a7c91df83dd4864/am_12.11.2015_um_09_25_37_hochladen.png) (Jörg)

![](https://trello-attachments.s3.amazonaws.com/56444c744b05ea43c006d714/1046x581/68d7a3f09585d73c6b24da20d608ded8/am_12.11.2015_um_09_23_17_hochladen.png)

Jörg ergänzt:
Das Gleiche passiert wenn man 2x auf Mitgliedschaft anfragen klickt:

Rückfrage von Frank:
@joerglohrer Wie kann man 2x auf Mitgliedschaft anfragen klicken? Nach dem ersten mal kommt dich "Anfrage gesendet" und nach Neuladen der Gruppenübersicht ebenfalls.

**Comment by johappel** [comment]
Kann den Bug nicht nachvollziehen.

**Comment by johappel** [comment]
Jörg kannst du noch einmal schauen, ob der Bug noch existiert?

**Comment by joerglohrer** [comment]
Ich habe mich als Testuser g7871070 angemeldet und die Mitgliedschaft bei der Gruppe ALPIKA-Online angefragt.
Nach nochmaligem klicken auf die Gruppe sieht der Screen so aus:
![image](https://cloud.githubusercontent.com/assets/1091954/11495695/8e8a86a6-980d-11e5-9fbe-cf981f3ccead.png)

**Comment by johappel** [comment]
Der Fehler tritt offenbar eher selten und nur unter bestimmten nicht nachstellbaren Bedingungen auf. Wir verfolgen das Problem erst einaml nicht mehr aktiv weiter.
