### ISSUE TITLE
Autoren ohne Zugriffsrechte bei http://rpq.pti-elementar.de/wp-admin/

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#192]
Benutzer mit Autorenrechten können bei  http://rpq.pti-elementar.de/wp-admin/ nicht auf's Dashboard zugreifen, Beiträge bearbeiten oder erstellen.
Ich vermute, dass es evtl. an Plugins (z.B. Benutzerrechte) liegen könnte - kann den Fehler jedoch nicht finden.
Kann bis Freitag geholfen werden?

**Comment by johappel** [comment]
Die Autorenschaft muss denjenigen Autoren zugeordnet werden, die die Beiträge bearbeiten können sollen. Momentan ist Simone in Allen Fällen dieser Autor. Deshalb kann kein anderer Autor den Artikel bearbeiten.
![image](https://user-images.githubusercontent.com/307023/30955572-56fc1cb0-a434-11e7-9aaa-b54763a1aae7.png)

**Comment by joerglohrer** [comment]
Nein, es muss an etwas anderem liegen. 
Ich habe "joergmustermann" zum Autor eines Beitrags gemacht:
![image](https://user-images.githubusercontent.com/1091954/30967745-77fea0f8-a45d-11e7-846e-6bdf1dff879d.png)

Trotzdem kommt der User weder in's Dashboard, noch in die Bearbeitungsansicht.

**Comment by joerglohrer** [comment]
Da sind so viele Plugins, dass ich da nicht durchblicke.
Evtl. der "Dashboard Access" das Problem?:
![image](https://user-images.githubusercontent.com/1091954/30967892-d22e4b64-a45d-11e7-8586-fd008d3aeffa.png)

**Comment by joerglohrer** [comment]
Ja, das war's!
Hab's auf "Authors, Editors, and Administrators geändert:
![image](https://user-images.githubusercontent.com/1091954/30967967-0c40203e-a45e-11e7-9097-6d494ad7e914.png)

**Comment by johappel** [comment]
Ok, welches Plugin ist das?

**Comment by joerglohrer** [comment]
Keine Ahnung - da scheint Andreas so einiges Installiert zu haben.

**Comment by joerglohrer** [comment]
auch die "Content Views" kenne ich nicht.

**Comment by johappel** [comment]
Hauptsache läuft :-)
