### ISSUE TITLE
Artikel mit sortierbaren Bildern im Anhang

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#193]
Nach Support-Anfrage wegen Bildergalerie habe ich in Franks Testgruppe einen Artikel mit Bilderupload angelegt:
https://gruppen.rpi-virtuell.de/docs/artikel-mit-sortierbaren-bildern-im-anhang/edit/
![image](https://user-images.githubusercontent.com/1091954/30953499-7e253536-a42c-11e7-945b-9cb9ce0f4304.png)
Die Bilder werden in umgekehrter Upload-Reihenfolge angezeigt und können nicht mehr sortiert werden. Einzige Möglichkeit für eine Bildergalerie (z.B. Tagungsdokumentation) in sortierter Reihenfolge wäre, jedes Bild einzeln im Artikel einzubinden.
Die Galeriefunktion der Anhänge ist jedoch schon gegeben:
![image](https://user-images.githubusercontent.com/1091954/30953614-f3d16cf0-a42c-11e7-8ac5-01e217140608.png)
Wäre es möglich, die Anhänge sortierbar zu machen, oder zumindest nach Namen statt nach Datum anzuzeigen?

**Comment by johappel** [comment]
Sortierung der Abhänge erfolgt jetzt nach Titel ab 
https://github.com/rpi-virtuell/rw-social-learner/releases/tag/1.2.9

Die Möglichkeit einer eigenen Sortierung nach Drag&Drop ist aufwendiger, wäre aber prinzipiell möglich.
