### ISSUE TITLE
Artikelupload und Englisch

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#194]
Bei einem neuen Artikel lassen sich bekanntermassen erst Dateien hochladen, wenn der Artikel zuvor gespeichert wurde. 
Jetzt ist dieser heikle Punkt momentan englisch:
![image](https://user-images.githubusercontent.com/1091954/31375109-c28275e0-ada0-11e7-9e93-37e5c199f000.png)
Im social-learner-de_DE.po ist das eigentlich übersetzt:
![image](https://user-images.githubusercontent.com/1091954/31375129-d1005470-ada0-11e7-8473-e7e5bac0eb11.png)
Muss es irgendwo anders korrigiert werden?

**Comment by staude** [comment]
Falsche Textdomain im Theme verwendet.

**Comment by empeiria** [comment]
![image](https://user-images.githubusercontent.com/1091954/31391820-e3afadaa-add7-11e7-8f48-ca0bc42c9104.png)
jetzt stimmt's :-)
