### ISSUE TITLE
blogs - Nach Anmeldung Overlay

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#196]
Nach jeder Anmeldung auf blogs.rpi-vrituell.de erscheint diese übergelagerte Fenster:
![image](https://user-images.githubusercontent.com/1091954/32056881-10e8f0f2-ba66-11e7-9f8b-95555a3a7b33.png)
Da das vermutlich jedem User so geht und ich nicht herausgefunden habe, von welchem Plugin es kommt... Was tun?

**Comment by staude** [comment]
Im Safari hab ich das nicht auf dem frank test blog

**Comment by joerglohrer** [comment]
wahrscheinlich hast du mal ein Häkchen gemacht bei "Don't show this message again"

**Comment by staude** [comment]
Ich kann mich nicht erinnern sowas schon mal gesehen zu haben
Welchen Browser hast du da?

**Comment by joerglohrer** [comment]
Das ist in Chrome - sieht für mich wie ein Front-Page-Editor aus

**Comment by staude** [comment]
evt in blogs die jetpack aktiviert haben?

**Comment by johappel** [comment]
Das ist keine Fehler sondern das plugin editus, das nur admins sehen
musst du etwas auf der Startseite verändern?

**Comment by joerglohrer** [comment]
ok :-) Nein, ich war nur irritiert das immer wegklicken zu müssen. Dann hat sich's erledigt.
