### ISSUE TITLE
Support-Ticket System

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/reliwerk#2]
Nutzen wir das System auch für den Support?
@beo9999 @johappel @staude

**Comment by johappel** [comment]
Ich denke, dass wir unseren Nutzern anbieten sollten, Fehler im neuen System hier einzutragen.
Allgemeine Supportanfragen finde ich hingegen hier nicht sinnvoll.

**Comment by johappel** [comment]
![2015-11-23_09h38_37](https://cloud.githubusercontent.com/assets/307023/11332453/19a01c9a-91c6-11e5-95ef-f005f2d1e29c.png)
