### ISSUE TITLE
Ich habe versucht und zwar fünfmal verschiedene Bilder, auf einer Unterseite einer Gruppe ein Bild hochzuladen. Es ist mir nicht gelungen!

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#20]
von Andrea

**Comment by johappel** [comment]
Gruppen haben eigentlich keine Unterseiten. Ich bräuchte einen Screenshot um zu verstehen, was gemeint ist.

**Comment by lehrruetsche** [comment]
Jetzt heißt es "Assoziierte Gruppe" früher hieß es Membergroups, glaube ich.
Jemand sagte mir, das sei eine Untergruppe. Ich habe auch eine angelegt, das ging. Sie heißt Philosophie, vielleicht siehst du sie. Aber sie lief dann wie eine eigenständige Gruppe. Das mit dem Bild hat jetzt im zweiten Anlauf geklappt.
Das Anlegen der Untergruppe wird übrigens mit "create a assoziierte Gruppe" eingeleitet. Warum heißt es nicht einfach "Untergruppe". Eine assozierte Gruppe ist eine Partnergruppe in meinen Augen.
