### ISSUE TITLE
Artikel anlegen funktioniert nicht mehr

### ISSUE THREAD

**Issue by beo9999** [rpi-virtuell/reliwerk#201]
Wenn man in einer Gruppe einen neuen Artikel erstellen will heißt es schon mal außer im Menü überall "Dokumente" statt "Artikel" (also mal wieder die falsche Übersetzung geladen).
Außerdem fehlt einiges im UI, vor allem der Button zum Speichern -> Artikel kann nicht angelegt werden.

getestet mit aktuellem Chrome (Android 7, Win10) und Firefox (Win10)

**Comment by johappel** [comment]
zunächst mal wieder Rollback auf 1.9.4

**Comment by beo9999** [comment]
Mit der Verwendung der offiziellen deutschen Übersetzungen ist das Problem wohl behoben.
