### ISSUE TITLE
Mitarbeiter können eigene Artikel nur bearbeiten, wenn sie diese selbst erstellt haben

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#203]
Ein Bug?
![image](https://user-images.githubusercontent.com/1091954/33844490-bcdbb13e-dea0-11e7-9b50-6446d09b0e1a.png)
Wenn der Admin eines Blogs einen Beitrag erstellt und als Autor einen Mitarbeiter einsetzt, kann dieser den Beitrag nicht bearbeiten. 
Nur selbst erstellte Beiträge eines Mitarbeiters sind bearbeitbar.
Mit der Rolle Autor funktioniert allerdings die Bearbeitung von vom Admin zugeteilten Beiträgen.

**Comment by johappel** [comment]
Das ist ein Missverständnis von der Rolle Mitarbeiter.
Kein Bug.
Die Rolle ist genauso korrekt.
Sonst könnte ein Mitarbeiter mit  seinen niedrigen Rechten, Artikel aller Autoren und Redakteure bearbeiten.

Die korrekte Vorgehensweise in der Bedienung wäre: Redakteur /Admin legt Artikel an und setzt als Autor den Mitarbeiter .

**Comment by joerglohrer** [comment]
Genau das funktioniert jedoch nicht!
WENN "Redakteur /Admin legt Artikel an und setzt als Autor den Mitarbeiter" DANN kann Mitarbeiter nicht bearbeiten.

**Comment by johappel** [comment]
Der Artikel darf bei einem Mitarbeiter noch nicht veröffentlicht sein!

**Comment by joerglohrer** [comment]
Du hast ja so recht! Der Knackpunkt ist der Entwurfsstatus! 👍 
Sorry für Stutzigkeit. Mein Anwenderfehler. #meaculpa
