### ISSUE TITLE
User kann Sichtbarkeit von Profil nur bei Anmeldung ändern - später nicht mehr

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#207]
Bei der Anmeldung kann die Sichtbarkeit des Namens noch ausgewählt werden:
![image](https://user-images.githubusercontent.com/1091954/34263497-093bc330-e670-11e7-81d3-7517780c652e.png)
Später im Profil, lässt sich das jedoch nicht mehr ändern:
![image](https://user-images.githubusercontent.com/1091954/34263441-d5c59e04-e66f-11e7-8c46-211ee50de6b9.png)

**Comment by johappel** [comment]
Guckst du :

![2017-12-21_17h33_48](https://user-images.githubusercontent.com/307023/34265152-6988b572-e675-11e7-8ae6-80a629d22f5c.gif)

**Comment by johappel** [comment]
Die Sichbarkeit des Namens darf natürlich nicht geändert werden (irgendwie logisch).
