### ISSUE TITLE
Viel Englisch

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#21]
Auf der Gruppenseite und auch auf der Untergruppenseite sind noch sehr viele englische Ausdrücke, schön gemischt mit deutschen. Zum Beispiel: "You hat die Gruppe sowieso erstellt". Auch oben im Menü abwechslungsweise englisch und deutsch. (Andrea)

![](https://trello-attachments.s3.amazonaws.com/5641c239a303de1bca778642/1920x1080/2cc15328e32171964df007eed8620ebb/Site_Group.png)

Frank:
BP Group Hierarchy wurde noch nicht in GlotPress importier, daher kann das Plugin noch nicht zentral auf translate.wordpress.org übersetzt werden. Übersetzung müsste via loco bei uns passieren (und sinnvollerweise danach dann die Übersetzung dem Autoren zukommen lassen)

Habe eine deutsche Sprachdatei angelegt. Wer sich berufen fühlt kann hier übersetzen http://reliwerk.de/wp-admin/admin.php?page=loco-translate&msginit=bp-group-hierarchy&name=bp-group-hierarchy%2Findex.php&type=plugin&common-locale=de_DE&custom-locale=de_DE&gforce=0

ping @joerglohrer :-)

**Comment by beo9999** [comment]
MIt dem Link oben lande ich hier und weiß nicht so genau, wie ich weiterkomme:
![2015-11-30 10_13_43-loco translation management - ubersetzungen verwalten reliwerk wordpress](https://cloud.githubusercontent.com/assets/12952801/11467828/2f7ea768-974b-11e5-8dc4-04b418d487be.png)

**Comment by staude** [comment]
@beo9999 http://reliwerk.de/wp-admin/admin.php?name=bp-group-hierarchy%2Findex.php&type=plugin&poedit=plugins%2Fbp-group-hierarchy%2Flanguages%2Fbp-group-hierarchy-de_DE.po&page=loco-translate ist der korrekte

**Comment by beo9999** [comment]
Bin mit den Übersetzungen soweit durch (für ein paar wenige Sachen wie "site root" hab ich erst mal das englische Original übernommen).
Jetzt muss man schauen, ob in der Live-Ansicht alles passt.
