### ISSUE TITLE
Blog-Suche

### ISSUE THREAD

**Issue by lehr-ruetsche** [rpi-virtuell/reliwerk#211]
Ich habe bei Blogs das Schlagwort "Reformation" eingeben, weil ich auf der Suche nach diesem Material war:
https://blogs.rpi-virtuell.de/reformation/

Aber es wurde kein Treffer gemeldet. Müsste nicht einfach dieses Material angezeigt werden?

**Comment by staude** [comment]
Da sind mehrere Denkfehler drin.

1. https://blogs.rpi-virtuell.de/reformation/ ist kein Material sondern die URL eines Blogs.
2. Die Suche durchsucht Beiträge und Seiten, nicht die Blogtitel 
3. Die Suche durchsucht jeweils das angewählte Blog, nicht alle Blogs innerhalb der Multisite

Selbs wenn es ein Plugin gäbe das auf der Startseite alle Blogs durchsucht. Will man so ein inkonsistentes Verhalten haben. Auf der Startseite alle Blogs durchsuchen, innerhalb eines Blogs nur noch das gewählte? Immer alle Blogs durchsuchen - versteht doch ein Blogbetreiber auch nicht, warum er dann Inhalte aller Blogs im Ergebnis hat.

**Comment by lehr-ruetsche** [comment]
okay
