### ISSUE TITLE
Benennung von heruntergeladenen Dokumenten aus den Gruppen

### ISSUE THREAD

**Issue by beo9999** [rpi-virtuell/reliwerk#217]
Wenn man die Anhänge eines Gruppen-Dokuments herunterlädt, dann werden z.B. .odt-Dateien als "Download.odt" und .docx-Dateien als "Download" heruntergeladen (statt mit dem ursprünglichen angezeigten Dateinamen). Insbesondere bei .docx ist das schlecht, weil der User dann das heruntergeladene Dokument von Hand umbenennen muss (Endung .docx wieder anfügen).

Verhalten getestet unter Win 10 mit aktuellem Chrome, z.B. hier: https://gruppen.rpi-virtuell.de/docs/test-download-anhaenge 

PS: Mit Firefox ist es noch merkwürdiger, da werden anscheinend zufällige Zeichenfolgen als Dateinamen vergeben, z.B. "aDdMNK7v.odt" bzw. "r+b6mYqK" für das .docx .

**Comment by staude** [comment]
BuddyPress setzt 
header('Content-Disposition: attachment; filename="filename.ext"');

soweit so gut, aber einige Browser scheint das nicht mehr zu interessieren.
Was bei einigen wiederum funktioniert ist html5 das a tag mit dem download attribute zu versehen.

Hab es in unser Theme "reingefrickelt"
