### ISSUE TITLE
Dokument hochladen in der Gruppe zu kompliziert

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#22]
Ich habe in meiner Gruppe versucht, ein Dokument hochzuladen. Solch ein einfacher Vorgang müsste meiner Meinung nach deutlich einfacher sein. Und das Ergebnis sah SO aus! (Andrea)

![](https://trello-attachments.s3.amazonaws.com/564a434b02562bc069674559/1920x1080/93cf4fe4587123eb6032a48abcb2b9d1/Doc_hochladen.png)

Wenn ich mir das genau ansehe, kann ich eigentlich gar kein Dokument hochladen, sondern muss immer einen Text schreiben, zu dem ich dann ein Dokument hochlade? Was mache ich falsch? (Andrea)

**Comment by johappel** [comment]
Der Vorteil dieses Verfahrens liegt auf der Hand: so werden alle hochgeladenen Dokumente von Anfang an in einen Kommuunikationskontext eingebettet, der anschließend auch kommentierbar und im Blick auf die Rechte flexibel händelbar ist.

Die Frage ist eher, wie lässt sich das duch eine gute Anleitung vermitteln?

**Comment by joerglohrer** [comment]
@johappel haben wir gestern ausführlich besprochen und kann geschlossen werden, oder?
