### ISSUE TITLE
Default options für neue Blogs

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#25]
Es braucht eine Routine, die bei der Einrichtung neuer Blogs alle nötigen Plugins aktiviert und die Optionen einträgt.

 - RW Auth Client
 - CAS Maestro
 - BuddyPress Captcha

**Comment by johappel** [comment]
Lösungsvorschlag eigenes Plugin 
- Multisiteplugin, das Default Installationen und Konfigurationen vornimmt
- Singlesiteplugin, das einmalig die Defaultkonfiguration ausführt und sich danach deaktiviert.

**Comment by johappel** [comment]
@staude macht das Multisiteplugin

**Comment by staude** [comment]
Erste Version liegt unter https://github.com/rpi-virtuell/rw-site-config
