### ISSUE TITLE
Verwirrende Häufung 

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#26]
Wenn ich ganz einfach auf meine Startseite gehe, stehen links die Dinge, die mich betreffen.
Die gleichen Dinge stehen aber unter dem Bild nochmals, zum Teil stehen dort aber auch Dinge, die links nicht im Menü kommen. So wichtige Punkte wie Docs findet man nach längerem suchen unter den kleinen ... Pünktchen.
Warum kann man nicht einfach unter dem Bild die Sachen lassen, die es links im Menü nicht gibt und die verwirrenden Doppelungen rausnehmen?

**Comment by joerglohrer** [comment]
ja, in der Tat: 
"Profil" "Benachrichtigungen", "Nachrichten", "Einstellungen" "Foren" "Freunde", "Gruppen" "Courses"
könnte aus der mittleren Navigation (unter dem Bild) ausgeblendet werden, weil es 1:1 über die Seitennavigation erreichbar ist. 
Dann hätte man "Aktivität" und dann gleich die "Docs" an erster Stelle in der mittleren Navigation.
Und übrig bleiben noch "Fotos" und "Einladungen verschicken".
Was meinst du @staude ?

**Comment by staude** [comment]
Was ist "meine Startseite" ?

Profilansicht meine Users auf Gruppen?
![2017-08-18_1122](https://user-images.githubusercontent.com/870951/29452696-9927cd52-8407-11e7-836e-166fd892887f.png)

Der Gruppenlink dort zeigt auf die Seite wo ich meine Gruppenmitgliedschaften sehe und Leute auch Einladen kann. Das ist was anderes als der /Gruppenbereich wo ich alle Gruppen sehen.

Und in meinem Profilbereich erwarte ich das ich da alles sehe und einstellen/ändern kann was mich Betrifft und nicht das das auf n verschiedene Bereiche verteilt ist - das wäre dann erst recht verwirrend.
