### ISSUE TITLE
Kurse

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#27]
Ich bin auf den zweiten Punkt im Menü gegangen "Kurse". Dort tauchen zwei Kurse auf, in denen ich aus irgendwelchen Gründen bin. Ich hätte sie gerne verlassen. Wie mache ich das? Ich bin dann auf das Menü unter dem Bild, dort wird unter ... ebenfalls Courses angeboten, es passiert aber nichts.
Ich habe auch nicht herausgefunden, wie ich einen neuen Kurs anbieten könnte.
Oder werden diese Kurse einfach allen angeboten und sie erscheinen, ob man will oder nicht?
Also: wie komme ich in einen Kurs? Wie beende ich die Teilnahme an einem Kurs? Wie biete ich selbst einen Kurs an?

Nun gibt es ganz oben im Überblicks-Menü auch Kurse. Dort kam ich ins Dashboard, aber nicht wirklich weiter.

**Comment by johappel** [comment]
Kein technisches Problem.  Zur Nutzung der Kurse bräuchte es noch ein Konzept.

**Comment by joerglohrer** [comment]
ja, Konzeptionsbedarf. 
Technisch gibt es allerdings auch noch Probleme: Wenn ich auf "Meine Kurse" klicke, lande ich bei @johappel Kursen auf http://reliwerk.de/members/joachim-happel/courses/ 
![image](https://cloud.githubusercontent.com/assets/1091954/11495264/0c1a780a-980a-11e5-84e0-ce6922e98971.png) da stimmt etwas nicht.

**Comment by johappel** [comment]
Es war im menü (buddypanel) der Link http://reliwerk.de/members/joachim-happel/courses/  hart eingetragen. Ich habe den Menüpunkt gelöscht. Für "meine Kurse" gibt es nur einen Link in der Profilnavigation, der noch nicht übersetzt ist: **courses**. Technisch gesehen ist aber alles in Ordnung. Ob man durch ein Plugin das dynamische Seitenmenü erweitern sollte, müsste man abwägen.
