### ISSUE TITLE
Ich kann auf meine eigenen Nachrichten antworten

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#28]
Leider habe ich noch nicht herausbekommen , wie man hier was anhängt, sonst hätte ich einen Screenshot mitgeschickt.
Aber ich habe eben an mein Testalterego eine Nachricht geschickt und postwendend öffnete sich darunter ein Feld, in dem ich antworten konnte.
Antworten auf eine Nachricht, die ich eben erst selbst geschrieben habe? Das macht für mich wenig Sinn.

**Comment by lehrruetsche** [comment]
Ein Freund fragte mich eben an, dass er so komische Kurse in seiner Gruppe hat, mit denen er nichts anfangen kann. Geht mir genauso...

**Comment by johappel** [comment]
@lehrruetsche  In welcher Gruppe tauchen die komischen kurse auf

**Comment by lehrruetsche** [comment]
Also, schreibe doch einfach mal an irgendjemand eine Nachricht, dann siehst du gleich, was ich meine. Du kannst auf deiner eigenen Seite auf die eben abgeschickte Nachricht antworten. Das macht doch wenig Sinn, oder?

**Comment by lehrruetsche** [comment]
![courses](https://cloud.githubusercontent.com/assets/15977289/11484524/c52bcfd0-97ae-11e5-9f78-0bfe139f6b40.png)

In diesen Kursen habe ich mich nie angemeldet. Nun kann es sein, dass ich aus Testzwecken angemeldet wurde oder aufgefordert wurde vor langer Zeit mich anzumelden.
Aber bei meinem Kollegen tauchen sie auch auf. Es ist verwirrend, zumal sie zu nicht sehr viel führen.
