### ISSUE TITLE
Benachrichtigung und Nachrichten

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#29]
Ich schicke und erhalten Nachrichten unter dem Menüpunkt "Nachrichten". Ich halte den Menüpunkt "Benachrichtigungen" für verwirrend und überflüssig.

**Comment by johappel** [comment]
Benachrichtungen kommen vom System (Systemmeldungen)
Nachrichten sind Botschaften von anderen Nutzern an mich.
