### ISSUE TITLE
Gruppenfunktionen Rückmeldung eines Kollegen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#33]
Folgende Mail habe ich eben bekommen:
kalle_0 hat dir eine neue Nachricht geschickt:

Betreff: Nachricht von Karl-Heinz

"Liebe Andrea,

da ich nicht mehr weiß, wie der Hauptverantwortich vom Reliwerk heißt, schreibe ich dir - du kannst es ja weitergeben.
Für mich (ohne Smartphone und Freunde....) ist alles wie Kraut und Rüben - aber das ist vermutlich mein Problem. Ich brauche zunächst die Möglichkeiten des Austausches nicht. Ich möchte Unterrichtseinheiten in "Ordnern" (Klasse 5, 6,7,8.... - Thema: Gott, Frieden,......) geordnet einstellen. Wie das auf der Plattform gehen soll, weiß ich nicht. Sollte es auch in Zukunft nicht gehen, nehme ich zunächst rpi-virtuell oder eine andere Plattform....

Ansonsten finde ich die Aufmachung ganz nett.

Lieber Gruß
Karl-Heinz"

**Comment by johappel** [comment]
Würde man das normalerweise nicht über eine Blog machen?
