### ISSUE TITLE
Vagrant Lösung ansehen

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/reliwerk#34]

**Comment by staude** [comment]
Getestet und Zusammenfassung an Intranda gemailt. Aktuell können die Daten vom Server noch nicht geholt werden.

**Comment by staude** [comment]
Grundsätzlich geht es. Muss noch ein ein paar Ecken rund gemacht werden. Ich kommuniziere das an Intranda. Werder das nächste Plugin dann schon mal in der Vagrant Box entwickeln.

**Comment by staude** [comment]
Feedback an Intranda geschickt

**Comment by staude** [comment]
Feedback an Intranda geschickt, Hinweis auf Hostsupdater Plugin gegeben

**Comment by staude** [comment]
Feedback an Intranda:

Ab und an kommt
tar: home/reliwerk/_sessions: file changed as we read it

---

Seit SSL Configänderung auf reliwerk startet der Apache in der VM nicht mehr.

**Comment by staude** [comment]
Tineoutprobleme. Mail an Intranda geschickt mit Problembeschreibung

**Comment by staude** [comment]
Bei Intranda nachgefragt

**Comment by lehrruetsche** [comment]
Bin ab jetzt verreist, ohne Laptop, nur Smartphone. Liebe Grüße Andrea

Am 09.12.2015 11:09 schrieb "Frank Staude" <notifications@github.com>:

**Comment by staude** [comment]
Lösung mit rsync und sshkeys läuft

**Comment by joerglohrer** [comment]
Ich kommentiere mal noch - zum Test der Rocket.Chat-Anbindung
