### ISSUE TITLE
Authentifizierungsystem hat irgend einen Bug 

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#36]
Ich habe mich mit "joergmustermann" auf http://reliwerk.de/open/ angemeldet. 
Dann kommt:
![image](https://cloud.githubusercontent.com/assets/1091954/11717106/8a3f5a8e-9f4e-11e5-92ae-d5d2f9828386.png)
und die URL schaltet auf https://login.reliwerk.de/wp-admin/
Ein User kommt hier nicht weiter.
Wenn ich jetzt manuell auf http://reliwerk.de/open/  gehe, bin ich immer noch nicht angemeldet - nach einem Klick auf Anmelden erfolgt der Login automatisch.
Das Gleiche unter reliwerk.de
Getestet mit Chrome.

**Comment by staude** [comment]
Kompabilitätsproblem nach update auf WordPress 4.4. Behoben
