### ISSUE TITLE
Freie Bildung - nicht für Redakteure

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#37]
Der User "joergmustermann" ist Redakteur bei http://reliwerk.de/open hat jedoch keine Navigationsmöglichkeit um zum Dashboard zu gelangen:
![image](https://cloud.githubusercontent.com/assets/1091954/11717250/86eae992-9f4f-11e5-99ad-7f6790964cd6.png)
Nur das manuelle Ändern der URL in http://reliwerk.de/open/wp-admin ermöglicht den Zugang.
Allen anderen Redakteuren geht es genauso.

**Comment by johappel** [comment]
doch:

![2015-12-11_01h43_40](https://cloud.githubusercontent.com/assets/307023/11732865/ba7d4242-9fa8-11e5-804b-80858d00d6a5.png)

**Comment by joerglohrer** [comment]
Nein!
joergmustermann war zwischenzeitlich zum Admin hochgestuft - das löst das Problem natürlich.
Jetzt wieder als Redakteur:
![image](https://cloud.githubusercontent.com/assets/1091954/11738367/7cc0d470-9fe2-11e5-84dc-db23d4d5de8b.png)

**Comment by staude** [comment]
Stimmt, der Redakteur Mustermann hat den Menüpunkt nicht.

![2017-08-29_1519](https://user-images.githubusercontent.com/870951/29822924-6c8ce132-8ccd-11e7-979e-90155e3e7153.png)

**Comment by staude** [comment]
Dazu ist die Rolle "Kurs Administrator" vorhanden.
