### ISSUE TITLE
We like(d) it

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/reliwerk#4]
In der Sidebar ist jetzt "We like(d) it"
![image](https://cloud.githubusercontent.com/assets/1091954/11332700/20e2b51a-91c8-11e5-9c32-646dd0a7b8cc.png)
1. Ist diese Funktion als als oberstes Element wichtig? @johappel 
2. Übersetzung!? @staude

**Comment by johappel** [comment]
Ich halte dynamische Elemente wichtiger als statische, das sie die Aufmerksamkeit des Nutzers auf neue Inhalte lenken. In diesem Fall auf die geliketen Aktivitäten der User, die sonst keine einfache erschließbaren Möglichkeiten haben, auf der Communityseite zu Wort zu kommen.
