### ISSUE TITLE
Login-Problem (auf FF)

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#41]
Wenn ich mich mit FF bei reliwerk auslogge und später wieder (ordnungsgemäß) einlogge, bekomme ich Folgendes angezeigt:
![loginproblem-ff](https://cloud.githubusercontent.com/assets/16247643/11732122/7a017f0a-9fa1-11e5-99c8-9e02a65e2f22.jpg)

Das Problem lässt sich austricksen:
1. Man schließt den Tab mit reliwerk
2. Man erstellt einen Tab mit reliwerk: Es erscheint die reliwerk-Startseite. Allerdings ist man ausgeloggt.
3. Man klickt auf "Einloggen": Man wird sofort - ohne zum Anmeldeschirm zu kommen - eingeloggt.

Obwohl ich auf meinen Workaround stolz bin, sollte man ihn den Anfängern auf reliwerk besser nicht zumuten.

**Comment by staude** [comment]
Inkompabilität nach Update auf WordPress 4.4. Ist Behoben.
