### ISSUE TITLE
Icons in der linken Spalte

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#42]
Dies ist nicht eigentlich ein Bug, aber muss trotzdem abgearbeitet werden.
Wenn man im neuen, schönen, aufgeräumten reliwerk das linke Menü einklappt, bleiben drei nicht besonders "sprechende" Symbole übrig: 
![icon-problem1](https://cloud.githubusercontent.com/assets/16247643/11732507/32cf2174-9fa5-11e5-9ae2-0b17e90cf647.jpg)

Dies wird vermutlich noch geändert werden?

**Comment by johappel** [comment]
Kann ich mich drum kümmern, wenn am ende sicher ist, wo die Navigationen wirklich landen.

**Comment by johappel** [comment]
es gibt eigentlich nur die Möglichkeit, dies im Backend unter 
 Boss Theme > Custom Codes > Javascript 
festzulegen 

`jQuery( document ).ready(function($) {`
    `$("#menu-titlebar li a:contains('Aktivitäten')").attr( 'class', 'fa-rss-square' );`
     `$("#menu-titlebar li a:contains('Mitglieder')").attr( 'class', 'fa-user' );`
    `$("#menu-titlebar li a:contains('Gruppen')").attr( 'class', 'fa-group' );`
`});`

![2016-07-15_12h40_12](https://cloud.githubusercontent.com/assets/307023/16871804/4b38c5be-4a89-11e6-822b-64f0819846f5.png)
