### ISSUE TITLE
Forumprobleme

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#45]
Ich persönlich halte ein gut funktionierendes Forum für extrem nützlich und wichtig.
Leider funktioniert das reliwerk-Forum nicht gut:

1) Ich als Nutzer kann keine Baumstruktur-Ansicht anzeigen. Wenn ich in einem Forumsthread weit oben eine Antwort auf einen Forumsbeitrag eingebe, landet sie ohne erkennbaren Zusammenhang mit dem Forumsbeitrag, auf den sie sich bezieht, ganz unten im Thread.

2) Es gibt einen "Dateianhänge"-Button, der offenbar tatsächlich Dateien anhängt ... zumindest werden diese Anhänge als hochgeladen angezeigt, solange man den Editiermodus nicht verlässt. Sobald der Forumsbeitrag jedoch abgeschickt wurde, verflüchtigt sich die angehängte Datei ins Nichts.

**Comment by johappel** [comment]
Upload im Forum funktioniert nicht.

**Comment by johappel** [comment]
Offenbar werden die Optionen des Plugins bei der Installation nicht automatisch gespeichert.
Nach dem Abspeichern der Optionen im Backend funtionierte der Upload. Ich würde sagen: "Gut zu wissen" und belasse es dabei.
