### ISSUE TITLE
Rechtschreibung und anderes

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#46]
Ein Konto habe ich bei der Bank, ich würde "Benutzerkonto" besser finden.
Screenshot anbei.
![konto](https://cloud.githubusercontent.com/assets/15977289/11761745/1ff9f9fe-a0cf-11e5-9234-9006c204e494.png)

Rechtschreibverbesserungen: 
![grammatik startseite 1](https://cloud.githubusercontent.com/assets/15977289/11761781/4375de38-a0d0-11e5-9432-70d5b84cb4a4.png)

Ist es Absicht, dass man sich einmal anmelden kann und einmal registrieren lässt???
![anmelden_registrieren](https://cloud.githubusercontent.com/assets/15977289/11761791/ca1dc400-a0d0-11e5-84c5-dcf09b433f08.png)

Was sind übrigens "digitale Distributionswege"?

**Comment by joerglohrer** [comment]
Slide überarbeitet - Rechtschreibung korrigiert - Buttons entfernt
"digitale Distributionswege" ersetzt durch "digitale Veröffentlichungen"
