### ISSUE TITLE
Gruppen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#47]
Menüpunkt Gruppen, rechtes Kästchen
Gruppenaktualisierungen: Welchen Zeitraum umfasst dieser Punkt?
Gruppenmitgliedschaften: Wenn man diesen Punkt anklickt, erfährt man, dass man Mitglied dieser Gruppe ist (meiner Meinung nach ziemlich überflüssig)
Update: Was unterscheidet "Update" von "Gruppenaktualisierungen"? Bei Update erscheinen Dinge, die ich vor längerer Zeit schon gemacht habe. Der einleitende Satz ist eine Mischung aus Englisch und Deutsch:
![you veroffentlichte](https://cloud.githubusercontent.com/assets/15977289/11761839/87321da6-a0d2-11e5-8be7-444fcb57ecc6.png)
Die zweite Hälfte der Angaben ist auf englisch:
![englisch in der zweiten halfte](https://cloud.githubusercontent.com/assets/15977289/11762010/a61e97f8-a0d7-11e5-943d-e037a4d59933.png)
New Docs
Wenn ich auf New Docs klicke und wiederum dort eine der Docs anklicke, sieht die Seite so aus:

![doc-seite gruppen](https://cloud.githubusercontent.com/assets/15977289/11762041/51ec0fec-a0d9-11e5-91a0-5318dc5bbdb1.png)
Ähnlich sieht die Seite unter Docs aus. Diese Seite müsste meiner Meinung nach unbedingt (!) verbessert werden, unübersichtlich, schlechte Optik, wo sind die wichtigen Dinge und wo die unwichtigen? Überlagerungen von Bild und Text usw.

Doc Comments: Ich hätte gerne eines der Dokumente kommentiert, habe aber nicht herausgefunden, wo.

**Comment by beo9999** [comment]
Die "You"-Problematik haben wir ja auch in #50. Schwierig im Deutschen. Eine Möglichkeit wäre, auch in diesem Fall den Usernamen anzuzeigen, ich weiß aber nicht, wie kompliziert und update-fest entsprechende Änderungen wären.
