### ISSUE TITLE
Zeige Details

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#48]
Wenn man in der Gruppenseite ein Doc angelegt hat oder ein Thema und auf den Titel klickt, kommt man auf eine neue Seite, siehe Anlage. Dort gibt es ein Angebot: Zeige Details. Da funktioniert nicht viel, wenn man da drauf klickt. Diese Seite finde ich insgesamt unübersichtlich. Und wo kommt man von dieser Seite aus hin? Sie ist wie eine Art Sackgasse.
![zeige details](https://cloud.githubusercontent.com/assets/15977289/11775291/d7ba9a02-a23d-11e5-87d3-cfe4855e1be0.png)

**Comment by staude** [comment]
Diese Ansicht gibt es so nicht mehr
