### ISSUE TITLE
Docs zu einem bereits bestehenden Titel hochladen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#49]
Wenn ich in einer meiner Gruppen zu einem meiner Titel ein weiteres Dokument hochladen will, dann geht das nicht. Es erscheint folgende Seite:
![dateien auswahlen](https://cloud.githubusercontent.com/assets/15977289/11775441/29b35578-a23f-11e5-85de-3634cf6c22a5.png)
Wenn ich aber mit einem neuen Titel diese Seite hochladen will, funktioniert es einwandfrei.
Ich fände es schön, wenn man zu einem bereits bestehenden Titel weitere Anlagen machen kann, denn dies ist die einzige Möglichkeit, bei Gruppendocs Ordnungen zu ermöglichen.

**Comment by staude** [comment]
Kann Problemlos .Doc einen zu einem Artikel hochladen. Wenn Problem noch besteht bitte neues Ticket machen und dann schauen wir mal gemeinsam per Bildschirmfreigabe.
