### ISSUE TITLE
Ihre t&auml;gliche Zusammenfassung der Gruppenaktivit&auml;t [reliWerk]

### ISSUE THREAD

**Issue by empeiria** [rpi-virtuell/reliwerk#5]
![image](https://cloud.githubusercontent.com/assets/1091954/11332757/95167d04-91c8-11e5-9105-c1e9cce2d7f5.png)
Bei den mails steht im Betreff:
"Ihre t&auml;gliche Zusammenfassung der Gruppenaktivit&auml;t [reliWerk]"
anstatt:
"Ihre tägliche Zusammenfassung der Gruppenaktivität bei reliWerk"

**Comment by johappel** [comment]
Evtl. Translation Pack überprüfen.

**Comment by joerglohrer** [comment]
gefunden, verbessert und abgeschlossen
