### ISSUE TITLE
Fehlende Übersetzung

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/reliwerk#50]
Fehlende Übersetzung "You ist der Gruppe xyz beigetreten" in der Startseite der Gruppe 

<img width="928" alt="ubersetzung" src="https://cloud.githubusercontent.com/assets/870951/11776691/6f2eb764-a249-11e5-91dc-f54ba6398cc1.png">

**Comment by beo9999** [comment]
hmm, schwierig im Deutschen. Mal schauen ob man da was finden kann das für beide Fälle passt.
"Du ist der Gruppe xyz beigetreten" oder "Du b ist der Gruppe xyz beigetreten"  ist auch nicht so toll... ;-)

**Comment by joerglohrer** [comment]
Benutzername wie bei den anderen wäre doch die naheliegende Lösung.

**Comment by beo9999** [comment]
Na ja, in buddypress-de_DE heißt der String halt "%1$s ist der Gruppe %2$s beigetreten". Das Ersetzen durch "You" in der eigenen Ansicht scheint automatisch zu passieren.

**Comment by staude** [comment]
Ersetzen kommt vom Buddyboss Wall Plugin, und kann da abgestellt werden.
![you](https://cloud.githubusercontent.com/assets/870951/11835911/377308fe-a3d7-11e5-9728-3500ce6b9449.png)

**Comment by joerglohrer** [comment]
closed ohne es zu ändern ;-) - habe ich nachgeholt.
