### ISSUE TITLE
Assoziierte Gruppe erstellen

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#52]
Ich habe eine Assoziierte Gruppe erstellt und könnte überhaupt nicht feststellen, wodurch sich diese Gruppe von einer ganz normal erstellten Gruppe unterscheidet. Es tauchen auch nirgends "Verbindungen" zur "Urgruppe" auf. Dann habe ich versucht, eine bereits bekannte Gruppe anzugeben und das ging auch nicht. Es war wieder eine neue Gruppe, die sich bildete, und zwar mit dem genau dem gleichen Namen der bereits bestehenden Gruppe "Jörg & Andrea". Man kann also den gleichen Gruppennamen mehrfach vergeben, zumindest wenn man dies über "Assoziierte Gruppe" macht. Bei Namen wie "Religionsunterricht" oder "Bildungsplan" könnte es meiner Meinung nach leicht zu Doppelungen kommen.

**Comment by staude** [comment]
in der Hauptgruppe gibt es einen extra Tab

<img width="1257" alt="2017-09-04_1609" src="https://user-images.githubusercontent.com/870951/30029920-7fe068a4-918b-11e7-9082-208c5794d561.png">

und in den Untergruppen ist oben eine art Brotkrümel-Navigation 
<img width="1397" alt="2017-09-04_1610" src="https://user-images.githubusercontent.com/870951/30029961-a01d5e74-918b-11e7-851b-877ce67f7370.png">
