### ISSUE TITLE
Löschen von Docs

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#54]
Man kann hochgeladene Seiten unter Docs nicht löschen. Im Forum geht es problemlos.
Bitte probiert es selbst mal aus. Man landet in einer Endlosschleife.

**Comment by deuxpont** [comment]
Problem bestätigt.

**Comment by staude** [comment]
Hat ggf mit dem Rechteproblem zu tun. Prüfen ob das von der Rolle des Users abhängig ist.

**Comment by staude** [comment]
Mit User lehr-ruetsche in der Frank Testgruppe erfolgreich durchprobiert.
