### ISSUE TITLE
Umlautproblem bei Docs Upload

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/reliwerk#58]
Dateinamen mit Umlaut werden gewandelt und können im Docs dann nicht heruntergeladen werden.

**Comment by johappel** [comment]
kann ich nachvollziehen
http://gruppen.rpi-virtuell.de/docs/teste-uploads-mit-umlauten/

**Comment by johappel** [comment]
Auf dem Server kommen sie Dateien korrekt an
![image](https://cloud.githubusercontent.com/assets/307023/16876138/1cabd596-4aa3-11e6-8a74-03625a9ced1d.png)

**Comment by johappel** [comment]
Auch in der DB ist alles korrekt
![image](https://cloud.githubusercontent.com/assets/307023/16876327/c1c209f6-4aa3-11e6-9195-9651220040c3.png)

**Comment by johappel** [comment]
Das Problem wird duch die php functiion basename verursacht
http://www.phpgangsta.de/vorsicht-bei-der-basename-funktion-und-umlauten

folgender Code in der wp-config.php löst das Problem, vorerst.

setlocale(LC_CTYPE, 'en_US.UTF8');

Mal sehen, ob es an anderen Orten Probleme wirft

**Comment by staude** [comment]
Auf http://php.net/manual/de/function.basename.php steht auch extra der Hinweis

basename() beachtet die Spracheinstellungen (locale); soll sie daher die korrekte Namensbasis in Pfaden mit einem Mehrbytezeichensatz erkennen, muss die passende Spracheinstellung (locale) mit der setlocale() Funktion gesetzt werden. 

Die basename Funktion von PHP verwendet intern (in C) memset zum umkopieren der Zeichen und versucht die länge von Multibyte Charactern zu ermitteln. Da ist es schon sinnvoll die locale zu setzen.  Es gibt auch wp_basename( $file ) in WordPress um das Problem zu umgehen. 

Ich probiere in einer ruhigen Minute mal aus ob es auch geht, wenn man im Docs alle basename durch wp_basename ersetzt - dann kann man das mal als PR zurückgeben.

**Comment by staude** [comment]
Siehe auch https://core.trac.wordpress.org/ticket/21217

**Comment by staude** [comment]
Pull Request eingereicht. 
https://github.com/boonebgorges/buddypress-docs/pull/581
