### ISSUE TITLE
Übersetzen

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#6]
![am_22 9 2015_um_20_10_30_hochladen 1](https://cloud.githubusercontent.com/assets/307023/11391668/7f83461a-9354-11e5-8a7c-34bf7656526e.png)

![](https://trello-attachments.s3.amazonaws.com/5602acd3d9f6c57a82e892f6/5602acd6d9f6c57a82e8949f/x/40aea8a4052fed793f72860d2336c415/photo.jpg)

![](https://trello-attachments.s3.amazonaws.com/5602acd3d9f6c57a82e892f6/5602acd6d9f6c57a82e8949f/558x397/6adc1eb5ee45898f4aee4654d05c8577/am_21.9.2015_um_10_42_31_hochladen.png)

Bei der Gruppenerstellung ist vieles noch englisch: https://trello-attachments.s3.amazonaws.com/55ffc2eee2990bff6498c64f/1515x635/394b58b28a890b5580924fa4f3bfb2d2/am_22.9.2015_um_20_10_30_hochladen.png

Aktiv - "Auf einen Blick"
besser "im Augenblick" oder "jetzt"

**Comment by staude** [comment]
Gerade mal den Prozess durchlaufen.

Es sind 3 Strings nicht übersetzt

Site Root - bei der Grouppen Hierarchy

No Email (users will read this group on the web - good for any group) - Bei den Einstellungen

Minimum role to associate Docs with this group: - Bei den Docs Dialog

**Comment by staude** [comment]
"Site Root" fixed in rw-bp-group-hierarchy 1.5.1

"No Email" bereits gefixt in der GitHub Version von buddypress-group-email-subscription, kommt mit dem nächsten Update

"Minimum role to associate Docs with this group" - Docs Übersetzungen aktualisiert
