### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#65]
@beo9999 findest du das?
![image](https://cloud.githubusercontent.com/assets/1091954/11854185/7f0ce8b8-a442-11e5-959e-a5eccf3d4845.jpeg)

**Comment by beo9999** [comment]
Solche Sachen finde ich in BuddyBoss Wall, aber da ist es eigentlich schon übersetzt.

**Comment by staude** [comment]
Wenn ich den Code richtig verstanden habe müsste es dieser String sein

<a href="%s" title="%s">%s</a> likes this

Die Sprachdatei war nicht aktuell mit dem Sourcecode. Dazu gibt es in Loco den  "Sync" Button.
Nach dem Sync haben wir nun 69 noch nicht übersetzte Zeichenketten in der Wall.

Den genannten hab ich jetzt mal übersetzt
<img width="888" alt="like" src="https://cloud.githubusercontent.com/assets/870951/11864438/c08c39d8-a49c-11e5-95f8-005bf3d7470c.png">
