### ISSUE TITLE
LearnDash - Topic Editor

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#66]
Es ist mir nicht möglich, im Topic-Editierfeld Links einzugeben. Im visuellen Modus passiert nichts, wenn man auf den Link-Button klickt. Wenn ich versuche, in den Textmodus umzuschalten, um den Link manuell einzugeben, passiert ebenfalls nichts: Das Textfenster wird gar nicht erst geöffnet.

K o r r e k t u r:
Es ist unter Chrome möglich, nicht aber unter Firefox.
Unter Firefox kann man auch in die Editoren anderer Bereiche von LearnDash keinen Hypertext schreiben, sondern nur reinen Text. 
Möglicherweise muss da etwas "restauriert"(?) werden.

**Comment by staude** [comment]
Unter Firefox 54.0.1 kein Problem feststellbar. Bei Bedarf bitte ein neues Ticket anlegen. Danke.
