### ISSUE TITLE
Slides werden gelöscht

### ISSUE THREAD

**Issue by johappel** [rpi-virtuell/reliwerk#7]
Wenn erstellte Slides mit QuickEdit überarbeitet und aktualisiert werden, löschen bliebt nur Titel und Beitragsbild bestehen. "Secodary Text" "Learn More" button und URL sind gelöscht.

![](https://trello-attachments.s3.amazonaws.com/56039e26c23606888eed43cc/1108x293/5a04faf9c99b1ab64cd45b52d71d696b/am_24.9.2015_um_08_54_33_hochladen.png)

**Comment by johappel** [comment]
Bitte noch einmal prüfen

**Comment by joerglohrer** [comment]
@johappel unter "joerglohrer" werden mir die Slides nicht angezeigt. Das Passwort für "wpadmin" wurde geändert. Schickst du mir das nochmal?
![image](https://cloud.githubusercontent.com/assets/1091954/11495187/6dd3e578-9809-11e5-839c-c9fa2fbff9f1.png)

**Comment by joerglohrer** [comment]
Slides sind seit Boss 2.0 jetzt nicht mehr als eigner Posttype zu bearbeiten - Damit kann das Problem nicht mehr auftreten:
![image](https://cloud.githubusercontent.com/assets/1091954/11496677/d63e0972-9813-11e5-97ef-62633544c659.png)
