### ISSUE TITLE
BuddyPress Register, check email

### ISSUE THREAD

**Issue by staude** [rpi-virtuell/reliwerk#71]
Im Registrierungsformular prüfen ob die Emailadresse schon in Benutzung ist.

**Comment by johappel** [comment]
ist das noch offen?

**Comment by staude** [comment]
Ist behoben
![2016-07-25_1150](https://cloud.githubusercontent.com/assets/870951/17097435/15e51f16-525e-11e6-956a-c9c267ccafc6.png)
