### ISSUE TITLE
"Freie Bildung" - sollte das nicht von "Reliwerk" kommen?

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#72]
![image](https://cloud.githubusercontent.com/assets/1091954/12191414/f586793e-b5d4-11e5-8564-3d8cccc64084.png)

**Comment by staude** [comment]
Ich spekuliere mal.

BuddyPress ist nicht Multisitefähig, sondern alls Sites haben zugriff darauf.
http://reliwerk.de/groups/frank-testgruppe/
ist auch unter Freie Bildung via
http://reliwerk.de/open/groups/frank-testgruppe/
erreichbar. Die Zusammenfassung wird via Cron angestossen. Bei den Emails wird als Absender dann das Blog genommen, welches gerade aufgerufen wurde um den Cronjob zu triggern.

Wenn wir später viele Blogs haben wird es immer wahrscheinlicher das da als Absender immer "zufällige" Namen stehen. 

Um das zu ändern müsste vor dem zusammenbau/versenden der Mail zum Hauptblog geswitcht werden, damit WP sich im korrekten Kontext befindet. Es muss also geschaut werden ob es einen passenden Hook gibt an den wir uns hängen können, zum Hauptblog umschalten, und nach dem generieren der Mail wieder zurückschalten zum aufgerufenen Blog.

Wenn ich das machen soll, bitte das Ticket mir zuweisen.

**Comment by staude** [comment]
Nach Migration der Site in eine Singlesite sollte das nun behoben sein.
