### ISSUE TITLE
Anmeldung Sicherheitsproblem!

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#75]
Gerade passiert:
Ich öffne firefox, gehe auf reliwerk.de und will mich als "joergmustermann" anmelden doch soweit komme ich gar nicht.
Ich klicke auf Anmelden - Nichts passiert.
Ich klicke nochmal auf Anmelden und bin angemeldet.
ABER ohne Eingabe von Benutzername und Kennwort sondern als "michael veeser-dombrowski"
und das ohne Einloggen, User-Switcher oder vorherige Admin-Rechte:
![image](https://cloud.githubusercontent.com/assets/1091954/12267317/d3172a08-b947-11e5-9e00-36e516637472.png)

**Comment by staude** [comment]
@empeiria Kannst du das reproduzieren? Ich nicht schaff es nicht

**Comment by joerglohrer** [comment]
@staude ich habe den User wieder abgemeldet - danach lief es wieder normal und war nicht reproduzierbar.
Was ist zu tun, wenn es wieder auftritt?

**Comment by staude** [comment]
Erinnern was du genau vorher gemacht hast. Spannend wäre ja was an Cookies usw VORHER da war.
und Genaue Uhrzeit/Datum festhalten damit man ggf auch noch mal im Logfile schauen kann was auf dem Server gerade los war.
