### ISSUE TITLE
Gruppe verlassen führt zu Fehlern

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#76]
Ich bin mit joergmustermann Admin in der gruppe reliwerk-erkundung.
Beim Verlassen der Gruppe öffnet sich der Dialog:
"Wollen Sie diese Gruppe wirklich verlassen?"
![image](https://cloud.githubusercontent.com/assets/1091954/12267486/a91bb7f4-b948-11e5-8c1d-f69973568a8a.png)
Nach Klick auf OK rotiert nur noch der Ladekreisel im Button:
![image](https://cloud.githubusercontent.com/assets/1091954/12267504/be79ac6e-b948-11e5-88f8-2388623d1a85.png)
und es folgt diese Meldung:
![image](https://cloud.githubusercontent.com/assets/1091954/12267456/7d1acc1c-b948-11e5-8f64-7b821228eeb5.png)
Danach bin ich nicht mehr Mitglied der Gruppe.

**Comment by staude** [comment]
Konnte ich mit meinem eigenen  Benutzer nicht reproduzieren in der genannten Gruppe.
@empeiria Welcher Benutzer war es und mit welchem Browser?

**Comment by staude** [comment]
@empeiria  Ah, hab es im letzten Bild gesehen, Reliwerk-Erkundung ist die Gruppe.

**Comment by staude** [comment]
Problem konnte mit den genannten Benutzer/Gruppenrechten reproduziert werden.

**Comment by staude** [comment]
Das Problem verursacht das Group Hierarchy Plugin. 

BP Group Hierarchy
Kompatibel bis: WP 3.8.2, BuddyPress 2.0-beta2
Zuletzt aktualisiert: vor 2 Jahren

Ich habe aber noch immer nicht ganz verstanden warum nur bei der einen Gruppe und was da genau schiefgeht, Offenbar ist das Plugin aber auch tot was die weiterentwicklung angeht. Das letzte Lebenszeichen des Authors im Supportforum seines Plugins ist über ein Jahr her.

**Comment by staude** [comment]
@johappel @empeiria wie damit umgehen?
