### ISSUE TITLE
"Diese Gruppe hat im Moment kein Forum."

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#77]
Wenn man unangemeldet auf ein Forum einer öffentlichen Gruppe zugreifen will kommt die Meldung:
"Diese Gruppe hat im Moment kein Forum." 
![image](https://cloud.githubusercontent.com/assets/1091954/12327241/a4ba07cc-bad5-11e5-8fc7-840198c13c19.png)
Das ist nicht richtig. Denn die Gruppe hat ja ein Forum. Allerdings ist es nicht erreichbar für unangemeldete Nutzer. Trotz "öffentlicher" Gruppe. 
Also entweder zugänglich machen oder die Meldung ändern?

**Comment by staude** [comment]
Kann ich mit http://reliwerk.de/groups/reliwerk-feedback/forum/ und http://reliwerk.de/groups/frank-testgruppe/forum/ nicht reproduzieren. 
@empeiria konnte deine Testgruppe nicht finden, giibt es die noch?

Möglicherweise gibt es das Problem nicht mehr in der jetzigen Singesiteinstanz.
Eventuell war aber auch die Gruppe in der anderen Site der MU angelegt.

**Comment by joerglohrer** [comment]
Die Testgruppe ist gelöscht und das Problem taucht jetzt auch nicht mehr auf.
Ich schließe den Issue und warte ab, ob es nochmal jemand vorbringt.
