### ISSUE TITLE
NUR firefox -> Profil Upload öffnet 2 Fenster 

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#83]
Nur das Untere funktioniert:
![image](https://cloud.githubusercontent.com/assets/1091954/12513950/e4fa436e-c120-11e5-9b7a-2bc76521b294.png)

**Comment by staude** [comment]
Ist reproduzierbar. Ist ja total schräg :) Aber beim Safari wählt man ein Bild aus, dann kommt dieser Dialog 
<img width="1647" alt="2016-01-25_1720" src="https://cloud.githubusercontent.com/assets/870951/12556789/f107474c-c387-11e5-91cc-ad22ecf7049e.png">
und das Bild ist weg.

**Comment by AndreasZiemer** [comment]
Doppeltes Fenster erscheint auch unter Chrome

**Comment by staude** [comment]
Ok, das oben genannte Verhalten ist was lokales bei mir. Doppelte Dialogfenster in FF und Chrome bleibt als Problem.

**Comment by staude** [comment]
Verursacher ist das BuddyBoss Media Plugin. 
Fehler wird mit dem nöchsten Update behoben
http://www.buddyboss.com/support-forums/topic/file-selection-popup-window-opens-twice/

Unsere aktuelle Version ist 3.1.6
