### ISSUE TITLE
Angenommene Einladungen

### ISSUE THREAD

**Issue by AndreasZiemer** [rpi-virtuell/reliwerk#85]
Noch eine gerade entdeckte Ungereimtheit: Ich sehe, bei den versandten Einladungen in den Gruppenraum, dass zwei Teilnehmerinnen die Einladung angenommen haben, sie erscheinen aber nicht im Aktivitätenprotokoll und auch in in der Teilnehmerliste. Warum ist das so?

**Comment by staude** [comment]
Ist aktuell so nicht reproduzierbar. Wenn das Problem noch einmal auftreten sollte, bitte ein neues Ticket erstellen inkl Links zur Gruppe und Teilnehmern. Danke.
