### ISSUE TITLE
Einladungen in Seminarräume

### ISSUE THREAD

**Issue by AndreasZiemer** [rpi-virtuell/reliwerk#86]
Habe eben festgestellt, dass ich Leute nur zu reliwerk einladen kann. Eine wiederholte Einladung in einen Seminarraum kann man irgendwie nicht verschicken.

**Comment by staude** [comment]
Kann ich nicht reproduzieren, habe mehrere Einladungen an eine Emailadresse versendet für verschieden Gruppen. 
Wenn das Problem noch einmal auftreten sollte, bitte ein neues Ticket erstellen. Danke.
