### ISSUE TITLE
Die Mitgliederverwaltung in "reliwerk Erkundung" zeigt keine Mitglieder an

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#88]
http://reliwerk.de/groups/reliwerk-erkundung/admin/manage-members/ (nur für GruppenAdmins zugänglich) ist leer
http://reliwerk.de/groups/reliwerk-erkundung/members/ (für alle zugänglich) zeigt die Mitglieder an.
![image](https://cloud.githubusercontent.com/assets/1091954/12583368/b60630b6-c442-11e5-9d7d-0f5ed03d6eb8.png)

**Comment by staude** [comment]
Mit https://github.com/rpi-virtuell/rw-social-learner als Thema ab 1.0.6 behoben.
