### ISSUE TITLE
Neue Foreneinträge produzieren HTML im Text

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/reliwerk#89]
Beispiel:
http://reliwerk.de/groups/eeb-online/forum/topic/das-bin-ich/#post-5544
![image](https://cloud.githubusercontent.com/assets/1091954/12586750/d4796234-c451-11e5-968c-d40b22b59008.png)
Liegt das daran, dass @johappel den Tiny MCE Editor deaktiviert hat?

**Comment by johappel** [comment]
Die Foreneintrage produzieren HTML, wenn der Tiny-MCE Advanced Editor falsch konfigueriet ist:
![2016-01-26_18h15_04](https://cloud.githubusercontent.com/assets/307023/12588415/da81fa36-c458-11e5-9d38-afb626faeb58.png)
