### ISSUE TITLE
LearnDash: Kursgruppen funktionieren nicht.

### ISSUE THREAD

**Issue by deuxpont** [rpi-virtuell/reliwerk#92]
Grundsätzlich: Am 13.2. startet der Kurs "Die 12er auf openreli", der eine geschlossene Lerngruppe behinhalten soll. 
Leider habe ich noch keine Ahnung, wie wir diese geschlossene Lerngruppe in den Kurs aufnehmen können.
Ich vermute stark, dass dies über die Gruppenfunktion geschieht, da dort die einzige Möglichkeit zu bestehen scheint, dass sich jemand anmelden kann.

Die Gruppenfunktion funktioniert aber nicht: Man kann zwar über diese Funktion eine Kursgruppe anlegen:

![screensh01](https://cloud.githubusercontent.com/assets/16247643/12642162/5da079f4-c5b4-11e5-88c3-bd39fb905c82.jpg)

Und die Gruppe wird auch tatsächlich erstellt:

![screensh02](https://cloud.githubusercontent.com/assets/16247643/12642177/74856fbc-c5b4-11e5-8233-bbfde00473db.jpg)

Unmittelbar nach dem Erstellen tauchte in der rechten Sidebar auf der Hauptseite des Kurses der Menüpunkt "Discussion" auf. Beim Anklicken wurde ich jedoch nicht in die Gruppe geleitet, sondern auf die Kurs-Überblickseite von "Freie Bildung".
Nachdem ich wieder den Kurs aufgerufen hatte, war der Menüpunkt verschwunden.
Und nachdem ich das Backend des Kurses aufgerufen hatte, war auch keine Kursgruppe eingetragen. Das dazugehörige Panel sah aus wie zuvor:

![screensh01](https://cloud.githubusercontent.com/assets/16247643/12642162/5da079f4-c5b4-11e5-88c3-bd39fb905c82.jpg)

Im Select-Dropdown waren nach wie vor keine Einträge enthalten.

Bitte Leute, kümmert euch bald drum ... sonst sieht unser Kursfeature gaaaanz übel aus vor die Leut ...

**Comment by johappel** [comment]
Die Gruppe daf nicht unsichtbar sein (ergibt keinen Sinn)
