### ISSUE TITLE
Freundschaftsanfrage

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#94]
ich glaube, ich habe das schon mal angefragt. Ich habe eine Freundschaftsanfrage von Eva-Maria Popp bekommen. Dies wird auch schön angezeigt. Siehe Bild.
![freundschaftsanfrage](https://cloud.githubusercontent.com/assets/15977289/12710775/2627c546-c8ba-11e5-8a4b-8b144ff7207f.png)
Wenn ich dieses Bild sehe, denke ich als normale Userin, dass ich auf "Übernehmen" klicken muss. Wenn ich darauf klicke, passiert aber nichts. Dann gehe ich auf "Aktion wählen", dort wird mir aber eine Annahme nicht angeboten. Also weiß ich erst mal nicht, was ich machen soll. Mit der Methode "Try and error" komme ich irgendwann darauf, dass ich die Anfrage selbst anklicken muss und DANN kann ich sie annehmen.  
Außerdem weiß ich nicht, warum neben BENACHRICHTIGUNG ein Kästchen zum Anklicken ist.

**Comment by staude** [comment]
Das ist die Ansicht der im System für dich vorhandenen Benachrichtigungen. Wie in anderen Ansichten auch, kannst du ein oder mehrere über die Checkbox markieren und dann über "aktion wählen" eine Massen oder Stapelverarbeitung machen, z.b. alle markierten löschen, als gelesen markieren.

> Außerdem weiß ich nicht, warum neben BENACHRICHTIGUNG ein Kästchen zum Anklicken ist
> Damit markierst du alle Benachrichtigungen in der Ansicht. 
