### ISSUE TITLE
Freundschaftsanfrage 2

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#95]
Ich habe mich völlig neu angemeldet. Den Namen gab es zwar theoretisch schon, aber ich wurde trotzdem wie eine Neuanmeldung registriert. 
Dann wollte ich an meine eigentliche Adresse eine Freundschaftsanfrage schicken und fand es logisch, dazu auf FREUNDE zu gehen. Dort habe ich gelesen, dass ich weder Freunde habe noch eine Freundschaftsanfrage. Das ist logisch. Aber warum kann ich dort keine Freundschaftsanfrage stellen? Ich habe noch nicht herausgefunden, wo ich das machen kann.

**Comment by staude** [comment]
In Auflistungen von Benutzer. Z.B. bei den Mitgliedern einer Gruppe
z.b. http://gruppen.rpi-virtuell.de/groups/support/members/
<img width="2076" alt="bildschirmfoto 2016-04-08 um 10 52 38" src="https://cloud.githubusercontent.com/assets/870951/14378963/09208936-fd78-11e5-8872-d435ae968c56.png">

oder in der Liste alle Benutzer http://gruppen.rpi-virtuell.de/members/
<img width="2059" alt="bildschirmfoto 2016-04-08 um 10 51 35" src="https://cloud.githubusercontent.com/assets/870951/14378910/e6c5be7e-fd77-11e5-8969-ca413184486c.png">
