### ISSUE TITLE
Grundsätzliches

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#96]
Grundsätzlich frage ich mich, ob das, was sich rechts öffnet, die Popuplist, nicht das Interessantere ist links im Menü stehen müsste.
Bei den Aktivitäten geht es mir auch so wie Birgit Bergs Gruppe, dass ich das nicht angenehm finden, jede Aktivität öffentlichzu sehen.

**Comment by staude** [comment]
???

**Comment by staude** [comment]
Ist das noch aktuell  @lehrruetsche

**Comment by lehr-ruetsche** [comment]
Nein, das habe ich jetzt anders gelöst.

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Dienstag, 5. September 2017 13:43
An: rpi-virtuell/reliwerk <reliwerk@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [rpi-virtuell/reliwerk] Grundsätzliches (#96)

 

Ist das noch aktuell @lehrruetsche <https://github.com/lehrruetsche>

**Comment by lehr-ruetsche** [comment]
Ich habe ausversehen beim falschen Issue etwas eingetragen. Aber ehrlich, ich weiß auch nicht mehr, an was ich am 2. Februar 2016 dran war. 

Das was ich anders gelöst habe, war die Frage nach dem Mailpoet. Das ist jetzt etwas Umständlicher als früher, aber es ist eine Lösung.

 

Von: Frank Neumann-Staude [mailto:notifications@github.com] 
Gesendet: Dienstag, 5. September 2017 13:43
An: rpi-virtuell/reliwerk <reliwerk@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [rpi-virtuell/reliwerk] Grundsätzliches (#96)

 

Ist das noch aktuell @lehrruetsche <https://github.com/lehrruetsche>
