### ISSUE TITLE
Mitgliederabmeldung erkennbar?

### ISSUE THREAD

**Issue by lehrruetsche** [rpi-virtuell/reliwerk#99]
In der Gruppe Philosophie wird Martin Wünsch auf der Gruppenstartseite als angemeldet angezeigt. Unter Mitglieder erscheint er aber nicht. Nun kann er sich ja abgemeldet haben. Kann ich als weiteres Gruppenmitglied solche Vorgänge irgendwie erkennen?

**Comment by staude** [comment]
Stimmt, Betreten erzeugt eine Aktivität, verlassen der Gruppe erzeugt aktuell keine Aktivität.

**Comment by staude** [comment]
Gruppenabmeldung wird ausgegeben in den Aktivitäten

![2017-09-06_1456](https://user-images.githubusercontent.com/870951/30113649-aef1b5d6-9315-11e7-9c6b-12e156f6498e.png)

Allerdings werden die Aktivitäten entfernt wenn weniger als 5 min zwischen An- und Abmeldung vergangen sind, um zu verhindern das mit ständigen An- und Abmelden die Aktivitätenliste gefluted wird.
